### PR TITLE
INTLY-9905: Remove all *PodCount alerts

### PR DESCRIPTION
**Pull request by b1zzu**
## Additional Information

https://issues.redhat.com/browse/INTLY-9905

The following alerts are removed:
* ThreeScalePodCount
* AMQOnlinePodCount
*  FuseOnlinePodCount
* ApicuritoPodCount
* CodeReadyPodCount
* LauncherPodCount
* ManagedServiceBrokerPodCount
* MiddlewareMonitoringPodCount
* SSOPodCount
* SolutionExplorerPodCount

## Verification Steps
As the verifier of the PR the following process should be done:

### Installation Verification
- Ensure the author of the PR has attached a log of the installation run from his branch to the jira or pr and check that it exited as expected.
- Verify the fresh installation is correct on cluster provided by PR author 
### Upgrade Verification
- After installation verification, notify the PR author to begin an upgrade on their cluster
- Ensure the developer of the PR has attached a log of the upgrade run from his branch to the jira or pr and check that it exited as expected. 
- If possible, look at the tasks that ran and see they match the PR
- Verify the upgrade is correct on cluster provided by PR author 

## Checklist

- [ ] Updated [Changelog](https://github.com/integr8ly/installation/blob/master/CHANGELOG.md)
- [ ] Tested Installation
- [ ] Tested Uninstallation
- [ ] Tested or Created follow on for Upgrade

Is an upgrade task required and are there additional steps needed to test this?
- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by mikenairn** [comment]
Does anything need to be done during an upgrade for these changes to be reflected on an existing cluster? @david-martin @jessesarn ?

**Comment by b1zzu** [comment]
@mikenairn don't think so because the alerts are overwritten on each updated:
https://github.com/integr8ly/installation/blob/d2b1c9b12ff26b9071879a26af4dde549957fdaa/playbooks/upgrade.yml#L54

**Comment by mikenairn** [comment]
@b1zzu Looks to be added alright, so it should be ok. I'd be in favour of just merging this and running a few install/upgrade tests once all the alert updates are back on master rather than wasting time doing a lot of manual testing on each PR. 

/lgtm

**Comment by b1zzu** [comment]
Installation Cluster: https://master.dbizzarr-51a4.open.redhat.com/console
Prometheus: https://prometheus-route-middleware-monitoring.apps.dbizzarr-51a4.open.redhat.com/alerts
Install Logs: [install.log](https://github.com/integr8ly/installation/files/5156637/install.log)

**Comment by b1zzu** [comment]
@mikenairn if you want also to verify the changes you can use the cluster I've posted above, I tested and it's working

**Comment by mikenairn** [comment]
@b1zzu There is still an ESPodCount, is that one to be left?

image

Also, where are the alerts that are superseding these ones "*ServiceEndpointDown" as described here https://issues.redhat.com/browse/INTLY-9905, i don't see any listed here https://prometheus-route-middleware-monitoring.apps.dbizzarr-51a4.open.redhat.com/alerts, shoudl i? @david-martin @jessesarn ?

**Comment by b1zzu** [comment]
@mikenairn The ServiceEndpointDown alerts will be introduced from this PR: https://github.com/integr8ly/installation/pull/1409

The ESPodCount will remain because it doesn't have a substitute, see here: https://issues.redhat.com/browse/INTLY-9905?focusedCommentId=14413156&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-14413156

**Comment by mikenairn** [comment]
@b1zzu Thanks, i see the other PR now, will just approve it also, appears to be tested and verified. Better just getting all these alert related things merged IMO so we can test them all together.

/lgtm
/approve

**Pull request merged**
