### PR TITLE
update data sync templates

### PR DESCRIPTION
**Pull request by wei-lee**
Replace PR #1181 

## Verification Steps
As the verifier of the PR the following process should be done:

### Installation Verification
- Ensure the author of the PR has attached a log of the installation run from his branch to the jira or pr and check that it exited as expected.
- Verify the fresh installation is correct on cluster provided by PR author 
### Upgrade Verification
- After installation verification, notify the PR author to begin an upgrade on their cluster
- Ensure the developer of the PR has attached a log of the upgrade run from his branch to the jira or pr and check that it exited as expected. 
- If possible, look at the tasks that ran and see they match the PR
- Verify the upgrade is correct on cluster provided by PR author 

## Is an upgrade task required and are there additional steps needed to test this?

- [x] Yes
- [ ] No

- [ ] Tested Installation
- [ ] Tested Uninstallation
- [ ] Tested or Created follow on for Upgrade

### CODE REVIEW

**Comment by wei-lee** [comment]
Upgrade logs. The upgrade failed, but it is due to a different issue. The data sync templates are updated.

If you login to this cluster `https://master.wat-ca97.open.redhat.com/` and check [this template](https://master.wat-ca97.open.redhat.com/console/project/openshift/edit/yaml?kind=Template&name=datasync-showcase-server&group=template.openshift.io&returnURL=project%2Fopenshift%2Fbrowse%2Fother%3Fkind%3DTemplate%26group%3Dtemplate.openshift.io), you will see the version is bumped to `0.9.2`.

```
PLAY [master] ************************************************************************************************************************************************************************************************************************************************************************************************************************************************************

TASK [include_role : openshift] ******************************************************************************************************************************************************************************************************************************************************************************************************************************************

TASK [openshift : Retrieve master configurations] ************************************************************************************************************************************************************************************************************************************************************************************************************************
ok: [master1.wat-ca97.internal]

TASK [openshift : add_host] **********************************************************************************************************************************************************************************************************************************************************************************************************************************************
changed: [master1.wat-ca97.internal]

TASK [include_role : mdc] ************************************************************************************************************************************************************************************************************************************************************************************************************************************************

TASK [mdc : Check master-config has been modified by the installer] ******************************************************************************************************************************************************************************************************************************************************************************************************
changed: [master1.wat-ca97.internal]

TASK [mdc : Remove mdc route to corsAllowedOrigins in master config, matching indentation of existing items] *************************************************************************************************************************************************************************************************************************************************************
changed: [master1.wat-ca97.internal]

TASK [Restart openshift master services] *********************************************************************************************************************************************************************************************************************************************************************************************************************************
changed: [master1.wat-ca97.internal] => (item=api)
changed: [master1.wat-ca97.internal] => (item=controllers)

TASK [Check if openshift master services are running] ********************************************************************************************************************************************************************************************************************************************************************************************************************
changed: [master1.wat-ca97.internal]

PLAY [master] ************************************************************************************************************************************************************************************************************************************************************************************************************************************************************

TASK [include_role : openshift] ******************************************************************************************************************************************************************************************************************************************************************************************************************************************

TASK [openshift : Retrieve master configurations] ************************************************************************************************************************************************************************************************************************************************************************************************************************
ok: [master1.wat-ca97.internal]

TASK [openshift : add_host] **********************************************************************************************************************************************************************************************************************************************************************************************************************************************
changed: [master1.wat-ca97.internal]

PLAY [localhost] *********************************************************************************************************************************************************************************************************************************************************************************************************************************************************

TASK [include_role : openshift] ******************************************************************************************************************************************************************************************************************************************************************************************************************************************

TASK [openshift : Password authentication] *******************************************************************************************************************************************************************************************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [openshift : Token authentication] **********************************************************************************************************************************************************************************************************************************************************************************************************************************
skipping: [127.0.0.1]

PLAY [localhost] *********************************************************************************************************************************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [include_role : prerequisites] **************************************************************************************************************************************************************************************************************************************************************************************************************************************

TASK [prerequisites : Ensure master params are present] ******************************************************************************************************************************************************************************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [prerequisites : Get target version] ********************************************************************************************************************************************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [prerequisites : fail] **********************************************************************************************************************************************************************************************************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [prerequisites : fail] **********************************************************************************************************************************************************************************************************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [set_fact] **********************************************************************************************************************************************************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [Get User RHSSO deployment desired replicas] ************************************************************************************************************************************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [Scale down User RH-SSO] ********************************************************************************************************************************************************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [Get UPS deployment desired replicas] *******************************************************************************************************************************************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [Scale down UPS] ****************************************************************************************************************************************************************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [Wait for User RH-SSO operator down] ********************************************************************************************************************************************************************************************************************************************************************************************************************************
FAILED - RETRYING: Wait for User RH-SSO operator down (50 retries left).
FAILED - RETRYING: Wait for User RH-SSO operator down (49 retries left).
FAILED - RETRYING: Wait for User RH-SSO operator down (48 retries left).
ok: [127.0.0.1]

TASK [Wait for UPS operator down] ****************************************************************************************************************************************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [Remove MDC namespace from User RH-SSO list] ************************************************************************************************************************************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [Remove MDC namespace from UPS list] ********************************************************************************************************************************************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [Get MDC ServiceInstances] ******************************************************************************************************************************************************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [Delete MDC ServiceInstances] ***************************************************************************************************************************************************************************************************************************************************************************************************************************************
changed: [127.0.0.1] => (item=admin-shared-2997 mdc-rtl4n)
changed: [127.0.0.1] => (item=customer-a-shar-b4c5 mdc-c6t6x)
changed: [127.0.0.1] => (item=customer-a-shar-b4c5 mdc-fh7pr)
changed: [127.0.0.1] => (item=evals01-shared-6a51 mdc-lxkk4)

TASK [include_role : mdc] ************************************************************************************************************************************************************************************************************************************************************************************************************************************************

TASK [mdc : Register available resources] ********************************************************************************************************************************************************************************************************************************************************************************************************************************
changed: [127.0.0.1] => (item=mobiledeveloperconsole)
changed: [127.0.0.1] => (item=grafanadashboards)
changed: [127.0.0.1] => (item=prometheusrules)
changed: [127.0.0.1] => (item=servicemonitors)

TASK [mdc : set_fact] ****************************************************************************************************************************************************************************************************************************************************************************************************************************************************
ok: [127.0.0.1] => (item={'_ansible_parsed': True, 'stderr_lines': [], '_ansible_item_result': True, u'end': u'2019-12-03 11:42:54.719524', '_ansible_no_log': False, u'stdout': u'mobiledeveloperconsole.mdc.aerogear.org/mdc', u'cmd': u'oc get mobiledeveloperconsole -n mobile-developer-console -o name', u'rc': 0, 'item': u'mobiledeveloperconsole', u'delta': u'0:00:00.194713', '_ansible_item_label': u'mobiledeveloperconsole', u'stderr': u'', u'changed': True, u'invocation': {u'module_args': {u'warn': True, u'executable': None, u'_uses_shell': True, u'_raw_params': u'oc get mobiledeveloperconsole -n mobile-developer-console -o name', u'removes': None, u'argv': None, u'creates': None, u'chdir': None, u'stdin': None}}, 'stdout_lines': [u'mobiledeveloperconsole.mdc.aerogear.org/mdc'], 'failed_when_result': False, u'start': u'2019-12-03 11:42:54.524811', '_ansible_ignore_errors': None, 'failed': False})
ok: [127.0.0.1] => (item={'_ansible_parsed': True, 'stderr_lines': [], '_ansible_item_result': True, u'end': u'2019-12-03 11:42:55.076550', '_ansible_no_log': False, u'stdout': u'grafanadashboard.integreatly.org/mdc-application\ngrafanadashboard.integreatly.org/mobile-developer-console-operator', u'cmd': u'oc get grafanadashboards -n mobile-developer-console -o name', u'rc': 0, 'item': u'grafanadashboards', u'delta': u'0:00:00.210107', '_ansible_item_label': u'grafanadashboards', u'stderr': u'', u'changed': True, u'invocation': {u'module_args': {u'warn': True, u'executable': None, u'_uses_shell': True, u'_raw_params': u'oc get grafanadashboards -n mobile-developer-console -o name', u'removes': None, u'argv': None, u'creates': None, u'chdir': None, u'stdin': None}}, 'stdout_lines': [u'grafanadashboard.integreatly.org/mdc-application', u'grafanadashboard.integreatly.org/mobile-developer-console-operator'], 'failed_when_result': False, u'start': u'2019-12-03 11:42:54.866443', '_ansible_ignore_errors': None, 'failed': False})
ok: [127.0.0.1] => (item={'_ansible_parsed': True, 'stderr_lines': [], '_ansible_item_result': True, u'end': u'2019-12-03 11:42:55.422616', '_ansible_no_log': False, u'stdout': u'prometheusrule.monitoring.coreos.com/mdc-monitoring\nprometheusrule.monitoring.coreos.com/mdc-operator-monitoring', u'cmd': u'oc get prometheusrules -n mobile-developer-console -o name', u'rc': 0, 'item': u'prometheusrules', u'delta': u'0:00:00.199610', '_ansible_item_label': u'prometheusrules', u'stderr': u'', u'changed': True, u'invocation': {u'module_args': {u'warn': True, u'executable': None, u'_uses_shell': True, u'_raw_params': u'oc get prometheusrules -n mobile-developer-console -o name', u'removes': None, u'argv': None, u'creates': None, u'chdir': None, u'stdin': None}}, 'stdout_lines': [u'prometheusrule.monitoring.coreos.com/mdc-monitoring', u'prometheusrule.monitoring.coreos.com/mdc-operator-monitoring'], 'failed_when_result': False, u'start': u'2019-12-03 11:42:55.223006', '_ansible_ignore_errors': None, 'failed': False})
ok: [127.0.0.1] => (item={'_ansible_parsed': True, 'stderr_lines': [], '_ansible_item_result': True, u'end': u'2019-12-03 11:42:55.762641', '_ansible_no_log': False, u'stdout': u'servicemonitor.monitoring.coreos.com/mobile-developer-console\nservicemonitor.monitoring.coreos.com/mobile-developer-console-operator', u'cmd': u'oc get servicemonitors -n mobile-developer-console -o name', u'rc': 0, 'item': u'servicemonitors', u'delta': u'0:00:00.194188', '_ansible_item_label': u'servicemonitors', u'stderr': u'', u'changed': True, u'invocation': {u'module_args': {u'warn': True, u'executable': None, u'_uses_shell': True, u'_raw_params': u'oc get servicemonitors -n mobile-developer-console -o name', u'removes': None, u'argv': None, u'creates': None, u'chdir': None, u'stdin': None}}, 'stdout_lines': [u'servicemonitor.monitoring.coreos.com/mobile-developer-console', u'servicemonitor.monitoring.coreos.com/mobile-developer-console-operator'], 'failed_when_result': False, u'start': u'2019-12-03 11:42:55.568453', '_ansible_ignore_errors': None, 'failed': False})

TASK [mdc : Delete available resources] **********************************************************************************************************************************************************************************************************************************************************************************************************************************
changed: [127.0.0.1] => (item=mobiledeveloperconsole.mdc.aerogear.org/mdc)
changed: [127.0.0.1] => (item=grafanadashboard.integreatly.org/mdc-application)
changed: [127.0.0.1] => (item=grafanadashboard.integreatly.org/mobile-developer-console-operator)
changed: [127.0.0.1] => (item=prometheusrule.monitoring.coreos.com/mdc-monitoring)
changed: [127.0.0.1] => (item=prometheusrule.monitoring.coreos.com/mdc-operator-monitoring)
changed: [127.0.0.1] => (item=servicemonitor.monitoring.coreos.com/mobile-developer-console)
changed: [127.0.0.1] => (item=servicemonitor.monitoring.coreos.com/mobile-developer-console-operator)

TASK [mdc : Delete mdc oauthclient] **************************************************************************************************************************************************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [mdc : Delete mdc operator] *****************************************************************************************************************************************************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [mdc : Wait for resources to be removed] ****************************************************************************************************************************************************************************************************************************************************************************************************************************
ok: [127.0.0.1] => (item=mobiledeveloperconsole.mdc.aerogear.org/mdc)
ok: [127.0.0.1] => (item=grafanadashboard.integreatly.org/mdc-application)
ok: [127.0.0.1] => (item=grafanadashboard.integreatly.org/mobile-developer-console-operator)
ok: [127.0.0.1] => (item=prometheusrule.monitoring.coreos.com/mdc-monitoring)
ok: [127.0.0.1] => (item=prometheusrule.monitoring.coreos.com/mdc-operator-monitoring)
ok: [127.0.0.1] => (item=servicemonitor.monitoring.coreos.com/mobile-developer-console)
ok: [127.0.0.1] => (item=servicemonitor.monitoring.coreos.com/mobile-developer-console-operator)

TASK [mdc : Get a list of all mobile CRs] ********************************************************************************************************************************************************************************************************************************************************************************************************************************
changed: [127.0.0.1] => (item=mobileclients)
changed: [127.0.0.1] => (item=keycloakrealms)
changed: [127.0.0.1] => (item=pushapplications)
changed: [127.0.0.1] => (item=androidvariants)
changed: [127.0.0.1] => (item=iosvariants)
changed: [127.0.0.1] => (item=mobilesecurityserviceapps)

TASK [mdc : set_fact] ****************************************************************************************************************************************************************************************************************************************************************************************************************************************************
ok: [127.0.0.1] => (item={'_ansible_parsed': True, 'stderr_lines': [], '_ansible_item_result': True, u'end': u'2019-12-03 11:43:03.162634', '_ansible_no_log': False, u'stdout': u'mobileclient.mdc.aerogear.org/test', u'cmd': u'oc get mobileclients -n mobile-developer-console -o name', u'rc': 0, 'item': u'mobileclients', u'delta': u'0:00:00.196389', '_ansible_item_label': u'mobileclients', u'stderr': u'', u'changed': True, u'invocation': {u'module_args': {u'warn': True, u'executable': None, u'_uses_shell': True, u'_raw_params': u'oc get mobileclients -n mobile-developer-console -o name', u'removes': None, u'argv': None, u'creates': None, u'chdir': None, u'stdin': None}}, 'stdout_lines': [u'mobileclient.mdc.aerogear.org/test'], 'failed_when_result': False, u'start': u'2019-12-03 11:43:02.966245', '_ansible_ignore_errors': None, 'failed': False})
ok: [127.0.0.1] => (item={'_ansible_parsed': True, 'stderr_lines': [], '_ansible_item_result': True, u'end': u'2019-12-03 11:43:03.509077', '_ansible_no_log': False, u'stdout': u'keycloakrealm.aerogear.org/test-realm', u'cmd': u'oc get keycloakrealms -n mobile-developer-console -o name', u'rc': 0, 'item': u'keycloakrealms', u'delta': u'0:00:00.195266', '_ansible_item_label': u'keycloakrealms', u'stderr': u'', u'changed': True, u'invocation': {u'module_args': {u'warn': True, u'executable': None, u'_uses_shell': True, u'_raw_params': u'oc get keycloakrealms -n mobile-developer-console -o name', u'removes': None, u'argv': None, u'creates': None, u'chdir': None, u'stdin': None}}, 'stdout_lines': [u'keycloakrealm.aerogear.org/test-realm'], 'failed_when_result': False, u'start': u'2019-12-03 11:43:03.313811', '_ansible_ignore_errors': None, 'failed': False})
ok: [127.0.0.1] => (item={'_ansible_parsed': True, 'stderr_lines': [], '_ansible_item_result': True, u'end': u'2019-12-03 11:43:03.847219', '_ansible_no_log': False, u'stdout': u'', u'cmd': u'oc get pushapplications -n mobile-developer-console -o name', u'rc': 0, 'item': u'pushapplications', u'delta': u'0:00:00.191906', '_ansible_item_label': u'pushapplications', u'stderr': u'', u'changed': True, u'invocation': {u'module_args': {u'warn': True, u'executable': None, u'_uses_shell': True, u'_raw_params': u'oc get pushapplications -n mobile-developer-console -o name', u'removes': None, u'argv': None, u'creates': None, u'chdir': None, u'stdin': None}}, 'stdout_lines': [], 'failed_when_result': False, u'start': u'2019-12-03 11:43:03.655313', '_ansible_ignore_errors': None, 'failed': False})
ok: [127.0.0.1] => (item={'_ansible_parsed': True, 'stderr_lines': [], '_ansible_item_result': True, u'end': u'2019-12-03 11:43:04.185604', '_ansible_no_log': False, u'stdout': u'', u'cmd': u'oc get androidvariants -n mobile-developer-console -o name', u'rc': 0, 'item': u'androidvariants', u'delta': u'0:00:00.191943', '_ansible_item_label': u'androidvariants', u'stderr': u'', u'changed': True, u'invocation': {u'module_args': {u'warn': True, u'executable': None, u'_uses_shell': True, u'_raw_params': u'oc get androidvariants -n mobile-developer-console -o name', u'removes': None, u'argv': None, u'creates': None, u'chdir': None, u'stdin': None}}, 'stdout_lines': [], 'failed_when_result': False, u'start': u'2019-12-03 11:43:03.993661', '_ansible_ignore_errors': None, 'failed': False})
ok: [127.0.0.1] => (item={'_ansible_parsed': True, 'stderr_lines': [], '_ansible_item_result': True, u'end': u'2019-12-03 11:43:04.525655', '_ansible_no_log': False, u'stdout': u'', u'cmd': u'oc get iosvariants -n mobile-developer-console -o name', u'rc': 0, 'item': u'iosvariants', u'delta': u'0:00:00.192916', '_ansible_item_label': u'iosvariants', u'stderr': u'', u'changed': True, u'invocation': {u'module_args': {u'warn': True, u'executable': None, u'_uses_shell': True, u'_raw_params': u'oc get iosvariants -n mobile-developer-console -o name', u'removes': None, u'argv': None, u'creates': None, u'chdir': None, u'stdin': None}}, 'stdout_lines': [], 'failed_when_result': False, u'start': u'2019-12-03 11:43:04.332739', '_ansible_ignore_errors': None, 'failed': False})
ok: [127.0.0.1] => (item={'_ansible_parsed': True, 'stderr_lines': [], '_ansible_item_result': True, u'end': u'2019-12-03 11:43:04.864981', '_ansible_no_log': False, u'stdout': u'', u'cmd': u'oc get mobilesecurityserviceapps -n mobile-developer-console -o name', u'rc': 0, 'item': u'mobilesecurityserviceapps', u'delta': u'0:00:00.193589', '_ansible_item_label': u'mobilesecurityserviceapps', u'stderr': u'', u'changed': True, u'invocation': {u'module_args': {u'warn': True, u'executable': None, u'_uses_shell': True, u'_raw_params': u'oc get mobilesecurityserviceapps -n mobile-developer-console -o name', u'removes': None, u'argv': None, u'creates': None, u'chdir': None, u'stdin': None}}, 'stdout_lines': [], 'failed_when_result': False, u'start': u'2019-12-03 11:43:04.671392', '_ansible_ignore_errors': None, 'failed': False})

TASK [mdc : Remove finalizers on CRs] ************************************************************************************************************************************************************************************************************************************************************************************************************************************
changed: [127.0.0.1] => (item=mobileclient.mdc.aerogear.org/test)
changed: [127.0.0.1] => (item=keycloakrealm.aerogear.org/test-realm)

TASK [mdc : Delete CRs] **************************************************************************************************************************************************************************************************************************************************************************************************************************************************
changed: [127.0.0.1] => (item=mobileclient.mdc.aerogear.org/test)
changed: [127.0.0.1] => (item=keycloakrealm.aerogear.org/test-realm)

TASK [mdc : Wait for resources to be removed] ****************************************************************************************************************************************************************************************************************************************************************************************************************************
ok: [127.0.0.1] => (item=mobileclient.mdc.aerogear.org/test)
ok: [127.0.0.1] => (item=keycloakrealm.aerogear.org/test-realm)

TASK [include_role : namespace] ******************************************************************************************************************************************************************************************************************************************************************************************************************************************

TASK [namespace : Delete namespaces mobile-developer-console] ************************************************************************************************************************************************************************************************************************************************************************************************************
changed: [127.0.0.1] => (item=mobile-developer-console)

TASK [mdc : Delete MDC CRDs] *********************************************************************************************************************************************************************************************************************************************************************************************************************************************
changed: [127.0.0.1] => (item=mobileclients.mdc.aerogear.org)
changed: [127.0.0.1] => (item=mobiledeveloperconsoles.mdc.aerogear.org)

TASK [Scale up User RH-SSO] **********************************************************************************************************************************************************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [Scale up UPS] ******************************************************************************************************************************************************************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [Wait for User RHSSO operator up] ***********************************************************************************************************************************************************************************************************************************************************************************************************************************
FAILED - RETRYING: Wait for User RHSSO operator up (50 retries left).
ok: [127.0.0.1]

TASK [Wait for UPS operator up] ******************************************************************************************************************************************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [include_role : mobile_security_service] ****************************************************************************************************************************************************************************************************************************************************************************************************************************

TASK [mobile_security_service : Delete project namespace: mobile-security-service] ***************************************************************************************************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [mobile_security_service : Delete cluster role binding] *************************************************************************************************************************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [mobile_security_service : Delete cluster role] *********************************************************************************************************************************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [mobile_security_service : Delete MSS CRDs] *************************************************************************************************************************************************************************************************************************************************************************************************************************
changed: [127.0.0.1] => (item=mobilesecurityserviceapps.mobile-security-service.aerogear.org)
changed: [127.0.0.1] => (item=mobilesecurityservicebackups.mobile-security-service.aerogear.org)
changed: [127.0.0.1] => (item=mobilesecurityservicedbs.mobile-security-service.aerogear.org)
changed: [127.0.0.1] => (item=mobilesecurityservices.mobile-security-service.aerogear.org)

TASK [Expose vars] *******************************************************************************************************************************************************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [Set eval_app_host var] *********************************************************************************************************************************************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [include_role : msbroker] *******************************************************************************************************************************************************************************************************************************************************************************************************************************************

TASK [msbroker : include_tasks] ******************************************************************************************************************************************************************************************************************************************************************************************************************************************
included: /home/ec2-user/installation/roles/msbroker/tasks/./apply_msbroker_template.yml for 127.0.0.1

TASK [msbroker : Get Launcher dashboard url] *****************************************************************************************************************************************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [msbroker : set_fact] ***********************************************************************************************************************************************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [msbroker : Get Che dashboard url] **********************************************************************************************************************************************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [msbroker : set_fact] ***********************************************************************************************************************************************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [msbroker : Include threescale route vars] **************************************************************************************************************************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [msbroker : Get 3scale dashboard url] *******************************************************************************************************************************************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [msbroker : set_fact] ***********************************************************************************************************************************************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [msbroker : Get apicurito dashboard url] ****************************************************************************************************************************************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [msbroker : set_fact] ***********************************************************************************************************************************************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [msbroker : Get shared Fuse dashboard url] **************************************************************************************************************************************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [msbroker : set_fact] ***********************************************************************************************************************************************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [msbroker : Get SSO route] ******************************************************************************************************************************************************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [msbroker : Get user SSO route] *************************************************************************************************************************************************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [msbroker : Get ups route] ******************************************************************************************************************************************************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [msbroker : Set ups url var] ****************************************************************************************************************************************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [msbroker : Set ups url var to empty string] ************************************************************************************************************************************************************************************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [msbroker : Expose vars] ********************************************************************************************************************************************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [include_role : imagestream_pull_secret] ****************************************************************************************************************************************************************************************************************************************************************************************************************************

TASK [imagestream_pull_secret : copy] ************************************************************************************************************************************************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [imagestream_pull_secret : Read the registry pull secret] ***********************************************************************************************************************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [imagestream_pull_secret : set_fact] ********************************************************************************************************************************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [imagestream_pull_secret : template] ********************************************************************************************************************************************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [imagestream_pull_secret : Create ImageStream Pull Secret] **********************************************************************************************************************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [msbroker : set_fact] ***********************************************************************************************************************************************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [msbroker : set_fact] ***********************************************************************************************************************************************************************************************************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [msbroker : Create managed service broker template in managed-service-broker] ***************************************************************************************************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [msbroker : Verify MSB is running] **********************************************************************************************************************************************************************************************************************************************************************************************************************************
FAILED - RETRYING: Verify MSB is running (50 retries left).
FAILED - RETRYING: Verify MSB is running (49 retries left).
ok: [127.0.0.1]

TASK [include_role : datasync] *******************************************************************************************************************************************************************************************************************************************************************************************************************************************

TASK [datasync : Install Mobile Developer Services Data Sync Application template] ***************************************************************************************************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [datasync : Install Mobile Developer Services Data Sync Showcase template] ******************************************************************************************************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [include_role : webapp] *********************************************************************************************************************************************************************************************************************************************************************************************************************************************

TASK [webapp : Construct openshift host string] **************************************************************************************************************************************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [webapp : Construct openshift oauth string] *************************************************************************************************************************************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [webapp : Get SSO route] ********************************************************************************************************************************************************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [webapp : Bump the Web App operator version to v0.0.36] *************************************************************************************************************************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [webapp : Wait for the new web app operator to be ready] ************************************************************************************************************************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [webapp : Generate WebApp custom resource template] *****************************************************************************************************************************************************************************************************************************************************************************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'cluster_type' is undefined"}

PLAY RECAP ***************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
127.0.0.1                  : ok=68   changed=44   unreachable=0    failed=1
master1.wat-ca97.internal  : ok=8    changed=6    unreachable=0    failed=0
```

**Comment by david-martin** [comment]
confirming the cluster_type var issue is resolved in #1184

**Pull request merged**
