### PR TITLE
Increased webapp wait for pod retries

### PR DESCRIPTION
**Pull request by obrienrobert**
## Additional Information
https://issues.redhat.com/browse/INTLY-7746

## Verification Steps
- Install via this branch
- Confirm that installation is successful, and the `wait for pods` step for the web app doesn't time out

Is an upgrade task required and are there additional steps needed to test this?
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by obrienrobert** [comment]
@philbrookes @jessesarn could I get one of you to take a look/approve this PR if you time, please? It's a relatively small change.

**Comment by philbrookes** [comment]
This looks good to me, is a change this trivial something we need to verify, or can we just go ahead on the verification done by Rob whilst developing?

**Pull request merged**
