### PR TITLE
Intly 7196

### PR DESCRIPTION
**Pull request by laurafitzgerald**
### Installation Verification
No installation changes here
### Upgrade Verification
Broken[ Upgrade logs](https://gist.github.com/laurafitzgerald/239c2c6ae8f9a3a7b5a07eef92211d8f) to start 

#### Image Verification
_Before upgrade_
Screenshot 2020-04-30 at 17 01 51

_After upgrade_
Screenshot 2020-04-30 at 17 15 54

#### Blackbox target update
Before Upgrade 
Screenshot 2020-05-01 at 14 45 51
After Upgrade
Screenshot 2020-05-01 at 15 14 22

Upgrade [logs](https://gist.github.com/laurafitzgerald/cb5572b7cc272493c4b7c62e88413d5f#file-intly-7196-upgrade-blackboxtarget-L273-L320)

Is an upgrade task required and are there additional steps needed to test this?
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by pawelpaszki** [comment]
Looks good to me, but will let @jessesarn to have a look at it as well and approve

**Comment by JameelB** [comment]
/hold 

hold on merging this until it's verified on osd https://github.com/integr8ly/installation/pull/1344

**Comment by laurafitzgerald** [comment]
Verification on rhmds-qe cluster
https://qe-tower.rhmw.io/#/jobs/playbook/2923

Verify images are updated.
Screenshot 2020-05-01 at 19 09 29

blackbox link updated.
Screenshot 2020-05-01 at 19 12 31

**Comment by laurafitzgerald** [comment]
ping @pawelpaszki @jessesarn see above. ^

**Pull request merged**
