### PR TITLE
Intly 9093 9097 manifest versions mismatch

### PR DESCRIPTION
**Pull request by david-martin**
## Additional Information
https://issues.redhat.com/browse/INTLY-9093
https://issues.redhat.com/browse/INTLY-9097

## Verification Steps

- Install from this branch
- Verify the versions of all products match what is in the manifest (can check linked issues for further details of how to check)

## Checklist

- [ ] Tested Installation
- [ ] Tested Upgrade

### CODE REVIEW

**Comment by damienomurchu** [comment]
:eyes: 

Fresh install running here: https://integreatly-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/pds-install-master-node/176/console
1.6.1 upgrade running here: 
1.7.0 upgrade running here: TODO

**Comment by damienomurchu** [comment]
Versions on fresh install ok:

```
                "name": "3scale",
                "version": "2.8.1.GA",
                "host": "https://3scale-admin.apps.croche-c26b.open.redhat.com"
                                            }
                        ,
                                {
                "name": "Identity Management",
                "version": "7.3.8.GA",
                "host": "https://sso-user-sso.apps.croche-c26b.open.redhat.com"
                                , "type": "keycloak"
                                                , "mobile": true
                            }
                        ,
```

**Comment by david-martin** [comment]
failure looks like a merge conflict.
Will rebase

```
Auto-merging roles/fuse_managed/tasks/wait_for_rollouts.yml\nCONFLICT (add/add): Merge conflict in roles/fuse_managed/tasks/wait_for_rollouts.yml\nAuto-merging roles/fuse_managed/tasks/upgrade.yml\nAuto-merging roles/backup/tasks/upgrade_images.yml\nCONFLICT (content): Merge conflict in roles/backup/tasks/upgrade_images.yml\nAuto-merging playbooks/upgrade.yml\nCONFLICT (content): Merge conflict in playbooks/upgrade.yml\nAuto-merging playbooks/group_vars/all/upgrade.yml\nCONFLICT (content): Merge conflict in playbooks/group_vars/all/upgrade.yml\nAuto-merging inventories/group_vars/all/manifest.yaml\nCONFLICT (content): Merge conflict in inventories/group_vars/all/manifest.yaml\nAuto-merging CHANGELOG.md\nCONFLICT (content): Merge conflict in CHANGELOG.md\nAutomatic merge failed; fix conflicts and then commit the result.\n
```

**Comment by david-martin** [comment]
@damienomurchu can you lgtm this again since i've rebased.
That should 🤞  fix the failing test

**Pull request merged**
