### PR TITLE
allow username to be overriden

### PR DESCRIPTION
**Pull request by maleck13**
allow the username to be set as a variable to different workshops can align this with their docs

### CODE REVIEW

**Comment by maleck13** [comment]
@mikenairn trying this out currently but does it look reasonable

**Comment by maleck13** [comment]
@pmccarthy If this works would like to get it into the workshop clusters.

**Comment by mikenairn** [comment]
@maleck13 Changes look fine, i remember wondering about his when i added these users, but think i was just trying to limit the amount of variables we had all over the place.

**Comment by maleck13** [comment]
verified on PDS cluster able to login with user1 and password also able to access enmasse and fuse

**Pull request merged**
