### PR TITLE
split mobile playbook to 2 parts and run them at different time

### PR DESCRIPTION
**Pull request by wei-lee**

### CODE REVIEW

**Comment by wei-lee** [comment]
ping @odra

**Comment by odra** [comment]
running it

**Comment by odra** [comment]
ups deployment failed:

```
E0808 09:21:45.473042       1 reflector.go:251] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to watch *v1alpha1.AndroidVariant: Get https://172.30.0.1:443/apis/push.aerogear.org/v1alpha1/androidvariants?resourceVersion=2371190&timeoutSeconds=492&watch=true: dial tcp 172.30.0.1:443: connect: connection refused
E0808 09:21:45.473067       1 reflector.go:251] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to watch *v1.PersistentVolumeClaim: Get https://172.30.0.1:443/api/v1/persistentvolumeclaims?resourceVersion=2378962&timeoutSeconds=324&watch=true: dial tcp 172.30.0.1:443: connect: connection refused
E0808 09:21:45.473084       1 reflector.go:251] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to watch *v1.DeploymentConfig: Get https://172.30.0.1:443/apis/apps.openshift.io/v1/deploymentconfigs?resourceVersion=2379858&timeoutSeconds=500&watch=true: dial tcp 172.30.0.1:443: connect: connection refused
E0808 09:21:45.473088       1 reflector.go:251] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to watch *v1.Secret: Get https://172.30.0.1:443/api/v1/secrets?resourceVersion=2380824&timeoutSeconds=365&watch=true: dial tcp 172.30.0.1:443: connect: connection refused
E0808 09:21:45.473100       1 reflector.go:251] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to watch *v1.ServiceAccount: Get https://172.30.0.1:443/api/v1/serviceaccounts?resourceVersion=2380086&timeoutSeconds=428&watch=true: dial tcp 172.30.0.1:443: connect: connection refused
E0808 09:21:45.473050       1 reflector.go:251] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to watch *v1beta1.CronJob: Get https://172.30.0.1:443/apis/batch/v1beta1/cronjobs?resourceVersion=2369707&timeoutSeconds=523&watch=true: dial tcp 172.30.0.1:443: connect: connection refused
E0808 09:21:45.473092       1 reflector.go:251] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to watch *v1.Route: Get https://172.30.0.1:443/apis/route.openshift.io/v1/routes?resourceVersion=2378968&timeoutSeconds=499&watch=true: dial tcp 172.30.0.1:443: connect: connection refused
E0808 09:21:45.473134       1 reflector.go:251] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to watch *v1alpha1.UnifiedPushServer: Get https://172.30.0.1:443/apis/push.aerogear.org/v1alpha1/unifiedpushservers?resourceVersion=2377085&timeoutSeconds=575&watch=true: dial tcp 172.30.0.1:443: connect: connection refused
E0808 09:21:45.473163       1 reflector.go:251] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to watch *v1.Service: Get https://172.30.0.1:443/api/v1/services?resourceVersion=2380199&timeoutSeconds=326&watch=true: dial tcp 172.30.0.1:443: connect: connection refused
E0808 09:21:45.473168       1 reflector.go:251] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to watch *v1alpha1.PushApplication: Get https://172.30.0.1:443/apis/push.aerogear.org/v1alpha1/pushapplications?resourceVersion=2376986&timeoutSeconds=569&watch=true: dial tcp 172.30.0.1:443: connect: connection refused
E0808 09:21:45.473170       1 reflector.go:251] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to watch *v1alpha1.IOSVariant: Get https://172.30.0.1:443/apis/push.aerogear.org/v1alpha1/iosvariants?resourceVersion=2375673&timeoutSeconds=471&watch=true: dial tcp 172.30.0.1:443: connect: connection refused
E0808 09:21:45.473441       1 reflector.go:251] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to watch *v1.ImageStream: Get https://172.30.0.1:443/apis/image.openshift.io/v1/imagestreams?resourceVersion=2368346&timeoutSeconds=478&watch=true: dial tcp 172.30.0.1:443: connect: connection refused
E0808 09:21:45.479610       1 reflector.go:134] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1beta1.MessagingUser: Get https://172.30.0.1:443/apis/user.enmasse.io/v1beta1/messagingusers?limit=500&resourceVersion=0: dial tcp 172.30.0.1:443: connect: connection refused
E0808 09:21:56.474247       1 reflector.go:134] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1alpha1.AndroidVariant: Get https://172.30.0.1:443/apis/push.aerogear.org/v1alpha1/androidvariants?limit=500&resourceVersion=0: net/http: TLS handshake timeout
E0808 09:21:56.475179       1 reflector.go:134] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1.PersistentVolumeClaim: Get https://172.30.0.1:443/api/v1/persistentvolumeclaims?limit=500&resourceVersion=0: net/http: TLS handshake timeout
E0808 09:21:56.476434       1 reflector.go:134] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1.DeploymentConfig: Get https://172.30.0.1:443/apis/apps.openshift.io/v1/deploymentconfigs?limit=500&resourceVersion=0: net/http: TLS handshake timeout
E0808 09:21:56.477686       1 reflector.go:134] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1.Secret: Get https://172.30.0.1:443/api/v1/secrets?limit=500&resourceVersion=0: net/http: TLS handshake timeout
E0808 09:21:56.478751       1 reflector.go:134] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1.ServiceAccount: Get https://172.30.0.1:443/api/v1/serviceaccounts?limit=500&resourceVersion=0: net/http: TLS handshake timeout
E0808 09:21:56.479958       1 reflector.go:134] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1beta1.CronJob: Get https://172.30.0.1:443/apis/batch/v1beta1/cronjobs?limit=500&resourceVersion=0: net/http: TLS handshake timeout
E0808 09:21:56.481008       1 reflector.go:134] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1.Route: Get https://172.30.0.1:443/apis/route.openshift.io/v1/routes?limit=500&resourceVersion=0: net/http: TLS handshake timeout
E0808 09:22:01.527925       1 reflector.go:134] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1beta1.MessagingUser: the server could not find the requested resource (get messagingusers.user.enmasse.io)
```

**Comment by wei-lee** [comment]
@odra that looks like an issue with the cluster, the api server is down maybe? Do you think it's due to the master restart command?

**Comment by odra** [comment]
looks to be a ups role issue, the operator has no permissions to wtach any of those resources

**Comment by odra** [comment]
ups role didn't fail as well, it just waited fo all readiness check retries and moved forward

**Comment by wei-lee** [comment]
@odra ok, can we merge this PR then, or are you still testing?

**Comment by odra** [comment]
still testing and got another error:
```
TASK [rhsso-user : Set new env var] **********************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "oc set env deployment/keycloak-operator 'CONSUMER_NAMESPACES=user-sso;mobile-developer-console' -n user-sso", "delta": "0:00:00.197697", "end": "2019-08-08 10:00:42.483107", "msg": "non-zero return code", "rc": 1, "start": "2019-08-08 10:00:42.285410", "stderr": "Error from server (NotFound): deployments.extensions \"keycloak-operator\" not found", "stderr_lines": ["Error from server (NotFound): deployments.extensions \"keycloak-operator\" not found"], "stdout": "", "stdout_lines": []}

```

@grdryn got this error in another cluster as well

**Comment by wei-lee** [comment]
@odra @grdryn can you try it again using this branch?

**Comment by grdryn** [comment]
Going to merge this so that I can rebase and deploy my branch on top

**Pull request merged**
