### PR TITLE
Removing monitoring steps done by the MDC operator

### PR DESCRIPTION
**Pull request by laurafitzgerald**
## Additional Information
https://issues.jboss.org/browse/INTLY-3701

- [x] Remove the resources and the steps
- [x] Update the MDC version once we've done a release

Related PRs
https://github.com/aerogear/mobile-developer-console-operator/pull/58
https://github.com/aerogear/mobile-developer-console-operator/pull/57

### Installation Verification
TODO:
- Ensure the author of the PR has attached a log of the installation run from his branch to the jira or pr and check that it exited as expected.
- Verify the fresh installation is correct on cluster provided by PR author 

**Expected Outcome**
The monitoring resources should be installed.

### Upgrade Verification
TODO:
- After installation verification, notify the PR author to begin an upgrade on their cluster
- Ensure the developer of the PR has attached a log of the upgrade run from his branch to the jira or pr and check that it exited as expected. 
- If possible, look at the tasks that ran and see they match the PR
- Verify the upgrade is correct on cluster provided by PR author 

## Is an upgrade task required and are there additional steps needed to test this?

- [ ] Yes
- [ ] No

- [ ] Tested Installation
- [ ] Tested Uninstallation
- [ ] Tested or Created follow on for Upgrade

### CODE REVIEW

**Comment by laurafitzgerald** [comment]
ping @grdryn only as fyi as this is at Draft status for now until we do a release of the operator.

**Comment by laurafitzgerald** [comment]
@davidffrench I'm in the process of deploying this now. Will ping you when it's ready.

**Comment by david-martin** [comment]
When this moves from WIP, it will need changes to the upgrade playbook to deploy the new version of the operator. This is important to ensure fresh installs end up looking the same as upgraded clusters

**Comment by laurafitzgerald** [comment]
@grdryn I think we can probably close this one now. Wdyt?

**Comment by grdryn** [comment]
Yeah, I think so :+1: 

/close

**Pull request closed without merging**
