### PR TITLE
ups-operator update 

### PR DESCRIPTION
**Pull request by fh-automatron**
Created automatically by jenkins

### CODE REVIEW

**Comment by mikenairn** [comment]
@secondsun This PR has all the updates required. Are there any upgrade tasks required for this.

**Comment by secondsun** [comment]
@mikenairn There shouldn't be any extra work for this PR.

**Comment by secondsun** [comment]
You deploy UPS with a image based on 2.4 instead of 2.3, it is forward compatible.

**Comment by maleck13** [comment]
I am not sure what that means? If I want to upgrade a customer from 2.3 of UPS to 2.4 what steps need to be followed? We will need to bring every cluster up to 2.4. These are the steps that would need to go in the upgrade playbook

**Comment by grdryn** [comment]
I think it's more useful to think about this in terms of upgrading the operator from 0.2.0 to 0.3.0, rather than upgrading UPS from version 2.3 to 2.4.0, since the operator should handle that part.

The main changes in 0.3.0 of the operator are:
- Remove imagestreams, & use a direct image references (currently a floating tag for UPS, hardcoded in a Go file, but hopefully a non-floating tag (if there's actually such a thing) soon or eventually a manifest digest.
- Add support for webpush

The addition of webpush here is the thing that's most likely going to need some upgrade logic (add webpush CRD to cluster, give operator SA cluster permissions to act on it), and equivalent install logic.

We've probably ignored doing this for now, given that there's so much other WIP in this operator and the other RHMDS operators.

I'm not sure what the `ups_release_tag` is used for.

**Comment by secondsun** [comment]
@grdryn `ups_release_tag` is used by the manifest that is consumed by MDC @wei-lee might be able to confirm this.

**Comment by wei-lee** [comment]
@secondsun looks like this one has duplicated contents of #1124, do we need both of them to be merged, or should we just merge #1124 instead?

**Comment by secondsun** [comment]
@wei-lee This is the PR that was generated by delorean.  The other PR modifies this PR because I don't have commit access to this branch

**Comment by secondsun** [comment]
Here are the updated update scripts and the log


```
[root@bastion 0 ~/installation master ↑·7|✚2]# ansible-playbook -i inventories/hosts playbooks/upgrades/upgrade.yaml

PLAY [master] ********************************************************************************************************************************************************************************************************************************

TASK [include_role : openshift] **************************************************************************************************************************************************************************************************************

TASK [openshift : Retrieve master configurations] ********************************************************************************************************************************************************************************************
ok: [master1.atlanta-3639.internal]

TASK [openshift : add_host] ******************************************************************************************************************************************************************************************************************
changed: [master1.atlanta-3639.internal]

PLAY [master] ********************************************************************************************************************************************************************************************************************************

TASK [include_role : openshift] **************************************************************************************************************************************************************************************************************

TASK [openshift : Retrieve master configurations] ********************************************************************************************************************************************************************************************
ok: [master1.atlanta-3639.internal]

TASK [openshift : add_host] ******************************************************************************************************************************************************************************************************************
changed: [master1.atlanta-3639.internal]

PLAY [localhost] *****************************************************************************************************************************************************************************************************************************

TASK [include_role : openshift] **************************************************************************************************************************************************************************************************************

TASK [openshift : Password authentication] ***************************************************************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [openshift : Token authentication] ******************************************************************************************************************************************************************************************************
skipping: [127.0.0.1]

PLAY [localhost] *****************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [include_role : prerequisites] **********************************************************************************************************************************************************************************************************

TASK [prerequisites : Ensure master params are present] **************************************************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [prerequisites : Get target version] ****************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [prerequisites : fail] ******************************************************************************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [prerequisites : fail] ******************************************************************************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [set_fact] ******************************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [include_role : ups] ********************************************************************************************************************************************************************************************************************

TASK [ups : Update ups resources] ************************************************************************************************************************************************************************************************************
changed: [127.0.0.1] => (item=https://raw.githubusercontent.com/aerogear/unifiedpush-operator/0.3.0/deploy/service_account.yaml)
changed: [127.0.0.1] => (item=https://raw.githubusercontent.com/aerogear/unifiedpush-operator/0.3.0/deploy/role.yaml)
changed: [127.0.0.1] => (item=https://raw.githubusercontent.com/aerogear/unifiedpush-operator/0.3.0/deploy/crds/push_v1alpha1_androidvariant_crd.yaml)
changed: [127.0.0.1] => (item=https://raw.githubusercontent.com/aerogear/unifiedpush-operator/0.3.0/deploy/crds/push_v1alpha1_webpushvariant_crd.yaml)
changed: [127.0.0.1] => (item=https://raw.githubusercontent.com/aerogear/unifiedpush-operator/0.3.0/deploy/crds/push_v1alpha1_iosvariant_crd.yaml)
changed: [127.0.0.1] => (item=https://raw.githubusercontent.com/aerogear/unifiedpush-operator/0.3.0/deploy/crds/push_v1alpha1_pushapplication_crd.yaml)
changed: [127.0.0.1] => (item=https://raw.githubusercontent.com/aerogear/unifiedpush-operator/0.3.0/deploy/crds/push_v1alpha1_unifiedpushserver_crd.yaml)

TASK [ups : patch new ups operator version] **************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [ups : Wait for the new unifiedpush operator to be ready] *******************************************************************************************************************************************************************************
changed: [127.0.0.1]

PLAY [localhost] *****************************************************************************************************************************************************************************************************************************

TASK [include_vars] **************************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [include_vars] **************************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [include_vars] **************************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [include_vars] **************************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [include_vars] **************************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [include_vars] **************************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [include_vars] **************************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [include_vars] **************************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [include_vars] **************************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [include_vars] **************************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [include_vars] **************************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [include_vars] **************************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [Set eval_app_host var] *****************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [Retrieve rhsso env vars] ***************************************************************************************************************************************************************************************************************
changed: [127.0.0.1] => (item=SSO_SERVICE_USERNAME)
changed: [127.0.0.1] => (item=SSO_SERVICE_PASSWORD)
changed: [127.0.0.1] => (item=SSO_ADMIN_USERNAME)
changed: [127.0.0.1] => (item=SSO_ADMIN_PASSWORD)

TASK [Set rhsso playbook vars] ***************************************************************************************************************************************************************************************************************
ok: [127.0.0.1] => (item={'_ansible_parsed': True, 'stderr_lines': [], '_ansible_item_result': True, u'end': u'2019-11-07 14:07:32.353003', '_ansible_no_log': False, u'stdout': u'', u'cmd': u'oc get dc/sso -o jsonpath=\'{.spec.template.spec.containers[0].env[?(@.name=="SSO_SERVICE_USERNAME")].value}\' -n sso', u'rc': 0, 'item': u'SSO_SERVICE_USERNAME', u'delta': u'0:00:00.197942', '_ansible_item_label': u'SSO_SERVICE_USERNAME', u'stderr': u'', u'changed': True, u'invocation': {u'module_args': {u'warn': True, u'executable': None, u'_uses_shell': True, u'_raw_params': u'oc get dc/sso -o jsonpath=\'{.spec.template.spec.containers[0].env[?(@.name=="SSO_SERVICE_USERNAME")].value}\' -n sso', u'removes': None, u'argv': None, u'creates': None, u'chdir': None, u'stdin': None}}, 'stdout_lines': [], u'start': u'2019-11-07 14:07:32.155061', '_ansible_ignore_errors': None, 'failed': False})
ok: [127.0.0.1] => (item={'_ansible_parsed': True, 'stderr_lines': [], '_ansible_item_result': True, u'end': u'2019-11-07 14:07:32.703241', '_ansible_no_log': False, u'stdout': u'', u'cmd': u'oc get dc/sso -o jsonpath=\'{.spec.template.spec.containers[0].env[?(@.name=="SSO_SERVICE_PASSWORD")].value}\' -n sso', u'rc': 0, 'item': u'SSO_SERVICE_PASSWORD', u'delta': u'0:00:00.195683', '_ansible_item_label': u'SSO_SERVICE_PASSWORD', u'stderr': u'', u'changed': True, u'invocation': {u'module_args': {u'warn': True, u'executable': None, u'_uses_shell': True, u'_raw_params': u'oc get dc/sso -o jsonpath=\'{.spec.template.spec.containers[0].env[?(@.name=="SSO_SERVICE_PASSWORD")].value}\' -n sso', u'removes': None, u'argv': None, u'creates': None, u'chdir': None, u'stdin': None}}, 'stdout_lines': [], u'start': u'2019-11-07 14:07:32.507558', '_ansible_ignore_errors': None, 'failed': False})
ok: [127.0.0.1] => (item={'_ansible_parsed': True, 'stderr_lines': [], '_ansible_item_result': True, u'end': u'2019-11-07 14:07:33.048160', '_ansible_no_log': False, u'stdout': u'admin', u'cmd': u'oc get dc/sso -o jsonpath=\'{.spec.template.spec.containers[0].env[?(@.name=="SSO_ADMIN_USERNAME")].value}\' -n sso', u'rc': 0, 'item': u'SSO_ADMIN_USERNAME', u'delta': u'0:00:00.191513', '_ansible_item_label': u'SSO_ADMIN_USERNAME', u'stderr': u'', u'changed': True, u'invocation': {u'module_args': {u'warn': True, u'executable': None, u'_uses_shell': True, u'_raw_params': u'oc get dc/sso -o jsonpath=\'{.spec.template.spec.containers[0].env[?(@.name=="SSO_ADMIN_USERNAME")].value}\' -n sso', u'removes': None, u'argv': None, u'creates': None, u'chdir': None, u'stdin': None}}, 'stdout_lines': [u'admin'], u'start': u'2019-11-07 14:07:32.856647', '_ansible_ignore_errors': None, 'failed': False})
ok: [127.0.0.1] => (item={'_ansible_parsed': True, 'stderr_lines': [], '_ansible_item_result': True, u'end': u'2019-11-07 14:07:33.400802', '_ansible_no_log': False, u'stdout': u'b2d6da1f18c544e9b087f9eb8ce49c07', u'cmd': u'oc get dc/sso -o jsonpath=\'{.spec.template.spec.containers[0].env[?(@.name=="SSO_ADMIN_PASSWORD")].value}\' -n sso', u'rc': 0, 'item': u'SSO_ADMIN_PASSWORD', u'delta': u'0:00:00.196523', '_ansible_item_label': u'SSO_ADMIN_PASSWORD', u'stderr': u'', u'changed': True, u'invocation': {u'module_args': {u'warn': True, u'executable': None, u'_uses_shell': True, u'_raw_params': u'oc get dc/sso -o jsonpath=\'{.spec.template.spec.containers[0].env[?(@.name=="SSO_ADMIN_PASSWORD")].value}\' -n sso', u'removes': None, u'argv': None, u'creates': None, u'chdir': None, u'stdin': None}}, 'stdout_lines': [u'b2d6da1f18c544e9b087f9eb8ce49c07'], u'start': u'2019-11-07 14:07:33.204279', '_ansible_ignore_errors': None, 'failed': False})

TASK [Retrieve cluster rhsso host] ***********************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [Set rhsso host var] ********************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [Retrieve launcher sso env vars] ********************************************************************************************************************************************************************************************************
changed: [127.0.0.1] => (item=SSO_SERVICE_USERNAME)
changed: [127.0.0.1] => (item=SSO_SERVICE_PASSWORD)
changed: [127.0.0.1] => (item=SSO_ADMIN_USERNAME)
changed: [127.0.0.1] => (item=SSO_ADMIN_PASSWORD)

TASK [Set launcher sso playbook vars] ********************************************************************************************************************************************************************************************************
ok: [127.0.0.1] => (item={'_ansible_parsed': True, 'stderr_lines': [], '_ansible_item_result': True, u'end': u'2019-11-07 14:07:34.325747', '_ansible_no_log': False, u'stdout': u'', u'cmd': u'oc get dc/launcher-sso -o jsonpath=\'{.spec.template.spec.containers[0].env[?(@.name=="SSO_SERVICE_USERNAME")].value}\' -n launcher', u'rc': 0, 'item': u'SSO_SERVICE_USERNAME', u'delta': u'0:00:00.198400', '_ansible_item_label': u'SSO_SERVICE_USERNAME', u'stderr': u'', u'changed': True, u'invocation': {u'module_args': {u'warn': True, u'executable': None, u'_uses_shell': True, u'_raw_params': u'oc get dc/launcher-sso -o jsonpath=\'{.spec.template.spec.containers[0].env[?(@.name=="SSO_SERVICE_USERNAME")].value}\' -n launcher', u'removes': None, u'argv': None, u'creates': None, u'chdir': None, u'stdin': None}}, 'stdout_lines': [], u'start': u'2019-11-07 14:07:34.127347', '_ansible_ignore_errors': None, 'failed': False})
ok: [127.0.0.1] => (item={'_ansible_parsed': True, 'stderr_lines': [], '_ansible_item_result': True, u'end': u'2019-11-07 14:07:34.679517', '_ansible_no_log': False, u'stdout': u'', u'cmd': u'oc get dc/launcher-sso -o jsonpath=\'{.spec.template.spec.containers[0].env[?(@.name=="SSO_SERVICE_PASSWORD")].value}\' -n launcher', u'rc': 0, 'item': u'SSO_SERVICE_PASSWORD', u'delta': u'0:00:00.199767', '_ansible_item_label': u'SSO_SERVICE_PASSWORD', u'stderr': u'', u'changed': True, u'invocation': {u'module_args': {u'warn': True, u'executable': None, u'_uses_shell': True, u'_raw_params': u'oc get dc/launcher-sso -o jsonpath=\'{.spec.template.spec.containers[0].env[?(@.name=="SSO_SERVICE_PASSWORD")].value}\' -n launcher', u'removes': None, u'argv': None, u'creates': None, u'chdir': None, u'stdin': None}}, 'stdout_lines': [], u'start': u'2019-11-07 14:07:34.479750', '_ansible_ignore_errors': None, 'failed': False})
ok: [127.0.0.1] => (item={'_ansible_parsed': True, 'stderr_lines': [], '_ansible_item_result': True, u'end': u'2019-11-07 14:07:35.039390', '_ansible_no_log': False, u'stdout': u'admin', u'cmd': u'oc get dc/launcher-sso -o jsonpath=\'{.spec.template.spec.containers[0].env[?(@.name=="SSO_ADMIN_USERNAME")].value}\' -n launcher', u'rc': 0, 'item': u'SSO_ADMIN_USERNAME', u'delta': u'0:00:00.206376', '_ansible_item_label': u'SSO_ADMIN_USERNAME', u'stderr': u'', u'changed': True, u'invocation': {u'module_args': {u'warn': True, u'executable': None, u'_uses_shell': True, u'_raw_params': u'oc get dc/launcher-sso -o jsonpath=\'{.spec.template.spec.containers[0].env[?(@.name=="SSO_ADMIN_USERNAME")].value}\' -n launcher', u'removes': None, u'argv': None, u'creates': None, u'chdir': None, u'stdin': None}}, 'stdout_lines': [u'admin'], u'start': u'2019-11-07 14:07:34.833014', '_ansible_ignore_errors': None, 'failed': False})
ok: [127.0.0.1] => (item={'_ansible_parsed': True, 'stderr_lines': [], '_ansible_item_result': True, u'end': u'2019-11-07 14:07:35.388251', '_ansible_no_log': False, u'stdout': u'm3QWDLclPm58QDS5GDFVrYvSTDnef6mN', u'cmd': u'oc get dc/launcher-sso -o jsonpath=\'{.spec.template.spec.containers[0].env[?(@.name=="SSO_ADMIN_PASSWORD")].value}\' -n launcher', u'rc': 0, 'item': u'SSO_ADMIN_PASSWORD', u'delta': u'0:00:00.195790', '_ansible_item_label': u'SSO_ADMIN_PASSWORD', u'stderr': u'', u'changed': True, u'invocation': {u'module_args': {u'warn': True, u'executable': None, u'_uses_shell': True, u'_raw_params': u'oc get dc/launcher-sso -o jsonpath=\'{.spec.template.spec.containers[0].env[?(@.name=="SSO_ADMIN_PASSWORD")].value}\' -n launcher', u'removes': None, u'argv': None, u'creates': None, u'chdir': None, u'stdin': None}}, 'stdout_lines': [u'm3QWDLclPm58QDS5GDFVrYvSTDnef6mN'], u'start': u'2019-11-07 14:07:35.192461', '_ansible_ignore_errors': None, 'failed': False})

TASK [set_fact] ******************************************************************************************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [include_role : customisation] **********************************************************************************************************************************************************************************************************

TASK [customisation : Create a list to store the manifest for each component that will be installed] *****************************************************************************************************************************************
ok: [127.0.0.1]

TASK [customisation : Get Integreatly WebApp route] ******************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [customisation : set_fact] **************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [customisation : set webapp component] **************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [customisation : set_fact] **************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [include_role : 3scale] *****************************************************************************************************************************************************************************************************************

TASK [3scale : Retrieve 3Scale admin auth token] *********************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [3scale : set_fact] *********************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [customisation : Retrieve 3Scale master auth token] *************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [customisation : Include threescale route vars] *****************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [customisation : Get threescale admin route] ********************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [customisation : set_fact] **************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [customisation : Get 3scale dashboard url] **********************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [customisation : set_fact] **************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [customisation : set threescale component] **********************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [customisation : set_fact] **************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [customisation : set_fact] **************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [customisation : Get apicurito ui secure route] *****************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [customisation : set_fact] **************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [customisation : set apicurito component] ***********************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [customisation : set_fact] **************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [customisation : Get codeready secure route] ********************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [customisation : set_fact] **************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [customisation : set che component] *****************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [customisation : set_fact] **************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [customisation : Find encrypted RH-SSO route] *******************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [customisation : Get RH-SSO secure route] ***********************************************************************************************************************************************************************************************
changed: [127.0.0.1 -> localhost]

TASK [customisation : set_fact] **************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [customisation : set rhsso component] ***************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [customisation : set_fact] **************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [customisation : Get Gitea route] *******************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [customisation : set_fact] **************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [customisation : set gitea component] ***************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [customisation : set_fact] **************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [customisation : Get launcher  route] ***************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [customisation : set_fact] **************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [customisation : set launcher component] ************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [customisation : set_fact] **************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [customisation : Get Fuse rest route] ***************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [customisation : set_fact] **************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [customisation : set fuse online component] *********************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [customisation : set_fact] **************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [customisation : set fuse component] ****************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [customisation : set_fact] **************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [customisation : Get enmasse rest route] ************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [customisation : set_fact] **************************************************************************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [customisation : set_fact] **************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [customisation : set enmasse component] *************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [customisation : set_fact] **************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [customisation : Get route for user-facing rhsso] ***************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [customisation : set_fact] **************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [customisation : Set User RHSSO component] **********************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [customisation : set_fact] **************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [customisation : Retrieve launcher sso hostvars] ****************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [customisation : set_fact] **************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [customisation : Generate custom inventory] *********************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [customisation : The manifests of the installed components] *****************************************************************************************************************************************************************************
ok: [127.0.0.1] => {
    "msg": [
        {
            "host": "https://tutorial-web-app-webapp.apps.atlanta-3639.open.redhat.com", 
            "name": "webapp", 
            "version": "2.18.7"
        }, 
        {
            "host": "https://3scale-admin.apps.atlanta-3639.open.redhat.com", 
            "name": "3scale", 
            "version": "2.6.0.GA"
        }, 
        {
            "host": "https://apicurito-app.apps.atlanta-3639.open.redhat.com", 
            "name": "apicurito", 
            "version": "0.2.18.Final"
        }, 
        {
            "host": "https://codeready-codeready.apps.atlanta-3639.open.redhat.com", 
            "name": "codeready", 
            "version": "1.2.0.GA"
        }, 
        {
            "host": "https://sso-sso.apps.atlanta-3639.open.redhat.com", 
            "name": "rh-sso", 
            "version": "7.3.2.GA"
        }, 
        {
            "host": "http://gitea.apps.atlanta-3639.open.redhat.com", 
            "name": "gitea", 
            "version": "1.6.0"
        }, 
        {
            "host": "https://launcher-launcher.apps.atlanta-3639.open.redhat.com", 
            "name": "launcher", 
            "version": "7224e235226ffa42135f148bacc409e9f7f402e4"
        }, 
        {
            "host": "https://syndesis-fuse.apps.atlanta-3639.open.redhat.com", 
            "name": "fuse_online", 
            "version": "7.4"
        }, 
        {
            "host": "", 
            "name": "fuse_openshift", 
            "version": "7.4"
        }, 
        {
            "host": "https://master.atlanta-3639.open.redhat.com:443/apis/enmasse.io", 
            "name": "enmasse", 
            "version": "1.2.2.GA"
        }, 
        {
            "host": "https://sso-user-sso.apps.atlanta-3639.open.redhat.com", 
            "mobile": true, 
            "name": "Identity Management", 
            "type": "keycloak", 
            "version": "7.3.2.GA"
        }
    ]
}

TASK [customisation : Generate custom manifest] **********************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [customisation : Check if webapp namespace exists] **************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [customisation : Create webapp namespace] ***********************************************************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [customisation : Add labels to namespace] ***********************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [customisation : Check if manifest secret exists] ***************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [customisation : Delete secret if it exists] ********************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [customisation : Create manifest secret] ************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [customisation : Check if manifest secret exists] ***************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [customisation : Delete secret if it exists] ********************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [customisation : Create manifest secret] ************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [customisation : Check if inventory secret exists] **************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [customisation : Delete inventory secret if it exists] **********************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [customisation : Create secret with custom inventory] ***********************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [customisation : remove generated template] *********************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [customisation : remove generated template] *********************************************************************************************************************************************************************************************
changed: [127.0.0.1]

PLAY [localhost] *****************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [include_role : prerequisites] **********************************************************************************************************************************************************************************************************

TASK [prerequisites : Verify oc version] *****************************************************************************************************************************************************************************************************
included: /root/installation/roles/prerequisites/tasks/oc_version.yml for 127.0.0.1

TASK [prerequisites : Get the target oc version to major version] ****************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [prerequisites : Verify target oc version matches a declared supported version] *********************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [prerequisites : Ensure master params are present] **************************************************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [prerequisites : Install Required Packages] *********************************************************************************************************************************************************************************************
included: /root/installation/roles/prerequisites/tasks/packages.yml for 127.0.0.1

TASK [prerequisites : Check if unzip is available] *******************************************************************************************************************************************************************************************
 [WARNING]: Consider using the unarchive module rather than running unzip.  If you need to use command because unarchive is insufficient you can add warn=False to this command task or set command_warnings=False in ansible.cfg to get rid
of this message.

ok: [127.0.0.1]

TASK [prerequisites : Install unzip if not present] ******************************************************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [prerequisites : Install gnu-tar required for MacOSX] ***********************************************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [prerequisites : include] ***************************************************************************************************************************************************************************************************************
included: /root/installation/roles/prerequisites/tasks/download_binary.yml for 127.0.0.1

TASK [prerequisites : Check that jq exists] **************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [prerequisites : download jq] ***********************************************************************************************************************************************************************************************************
skipping: [127.0.0.1]

PLAY [master] ********************************************************************************************************************************************************************************************************************************

TASK [include_role : openshift] **************************************************************************************************************************************************************************************************************

TASK [openshift : Retrieve master configurations] ********************************************************************************************************************************************************************************************
ok: [master1.atlanta-3639.internal]

TASK [openshift : add_host] ******************************************************************************************************************************************************************************************************************
changed: [master1.atlanta-3639.internal]

PLAY [localhost] *****************************************************************************************************************************************************************************************************************************

TASK [include_role : openshift] **************************************************************************************************************************************************************************************************************

TASK [openshift : Password authentication] ***************************************************************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [openshift : Token authentication] ******************************************************************************************************************************************************************************************************
skipping: [127.0.0.1]

PLAY [localhost] *****************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [include_vars] **************************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [include_vars] **************************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [include_vars] **************************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [Retrieve current manifest] *************************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [Decode webapp secret] ******************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [set_fact] ******************************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [Get Mobile Security Service rest route] ************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [set_fact] ******************************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [Set Mobile Security Service component] *************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [set_fact] ******************************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [Get Unified Push Server route] *********************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [set_fact] ******************************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [Set Unified Push Server component] *****************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [set_fact] ******************************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [Get mdc secure route] ******************************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [set_fact] ******************************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [Set Mobile Developer Console component] ************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [set_fact] ******************************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [Add mobile items to manifest definition] ***********************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [Write config to file] ******************************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [Check if manifest secret exists] *******************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [Delete secret if it exists] ************************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [Create manifest secret] ****************************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [Check if manifest secret exists] *******************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [Delete secret if it exists] ************************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [Create manifest secret] ****************************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [include_role : mdc] ********************************************************************************************************************************************************************************************************************

TASK [mdc : Get mdc deployment config] *******************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [mdc : patch mdc dc] ********************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [mdc : Write new dc definition file] ****************************************************************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [mdc : Apply dc changes] ****************************************************************************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [mdc : Wait for mdc rollout] ************************************************************************************************************************************************************************************************************
skipping: [127.0.0.1]

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************
127.0.0.1                  : ok=130  changed=51   unreachable=0    failed=0   
master1.atlanta-3639.internal : ok=6    changed=3    unreachable=0    failed=0   


```

**Comment by secondsun** [comment]
I guess we need someone to add the lgtm label?

**Comment by grdryn** [comment]
I have submitted #1157 to revert this change, since we're not going to upgrade to the new version of UPS in RHMI 1.6.

**Pull request merged**
