### PR TITLE
INTLY-1153 first uninstall the config console

### PR DESCRIPTION
**Pull request by tremes**

### CODE REVIEW

**Comment by tremes** [comment]
It worked on my PDS - https://integreatly-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/uninstallation-pipeline/735/console

**Comment by JameelB** [comment]
I don't think this would work if the web console customization wasn't installed in the first place/has been removed before running the uninstall. I think we should first check if the console-config namespace is there before running this task.

**Comment by tremes** [comment]
Ahh ok I thought the console-config is always installed.

**Comment by JameelB** [comment]
I'm not sure if it will always be, but in cases where the installation fails before it reaches to the point where it installs the web console customization the uninstaller will fail. Maybe it's a bit of an edge case?

**Comment by tremes** [comment]
Actually you're right. Good point. Feel free to close and update it.

**Pull request closed without merging**
