### PR TITLE
update booster catalog tag

### PR DESCRIPTION
**Pull request by pb82**
Update to latest launcher booster catalog

Verification steps:

1. Run WT2
2. When you select the Fuse runtime, make sure its listed as `Fuse 7.4` in the dropdown.

Upgrade:

1. Install 1.4.1
2. Run the upgrade playbook
3. Check the `launcher` configmap in the launcher namespace. The key `launcher.backend.catalog.git.ref` needs to have a value of `integreatly-1.5.0`.

### CODE REVIEW

**Comment by davidffrench** [comment]
👀

**Comment by davidffrench** [comment]
@pb82 just to confirm. Is this where it should be shown as 7.4?


Is there anywhere else to be checked?

**Comment by pb82** [comment]
@davidffrench yes, thats it

**Comment by davidffrench** [comment]
@pb82 is this ready for me to test an upgrade?

**Comment by davidffrench** [comment]
hey @pb82 . On upgrade, I have verified that the gitRef is `integreatly-1.5.0` in the configmap. However, I thought it was an issue with my cluster but there seems to be an issue with the change on upgrade.I didn't get this on install, when logging into launcher I get "WE'RE SORRY ...
Unexpected error when authenticating with identity provider"

**Pull request merged**
