### PR TITLE
amq-online update

### PR DESCRIPTION
**Pull request by fh-automatron**
Created automatically by jenkins

### CODE REVIEW

**Comment by jhellar** [comment]
LGTM. Verified on PDS cluster by following WT1A.

**Comment by pmccarthy** [comment]
Validated on my side also. Both install and upgrade is working as expected. Completed a walkthrough for verification.

@dimitraz should be good to merge 👍

**Comment by dimitraz** [comment]
@jhellar @pmccarthy  do one of you mind adding a lgtm label?

**Pull request merged**
