### PR TITLE
remove user namespaces after integr8ly namespaces

### PR DESCRIPTION
**Pull request by philbrookes**
@sedroche

### CODE REVIEW

**Comment by maleck13** [comment]
What is the reason for the change?

**Comment by philbrookes** [comment]
the block of code removing all the namespaces is deleting the rhsso namespace before it's uninstall playbook has run.

The uninstall playbook needs to delete the RHSSO resources in a particular order for it to work correctly.

This block of code was only ever intended to remove users namespaces, not integreatly services namespaces.

**Comment by sedroche** [comment]
@maleck13 This is in relation to https://issues.jboss.org/browse/INTLY-592

**Comment by tremes** [comment]
I am checking that on QE Pony

**Pull request merged**
