### PR TITLE
Fix uninstall playbook to be executed from MacOSX

### PR DESCRIPTION
**Pull request by camilamacedo86**
## Motivation
Allow executing the uninstall playbook from MacOSX SO. After this PR the uninstall playbook should work perfectly well from the RHEL/Linux/bastion station and from outside it in a MacOSX SO.

Issue: https://github.com/integr8ly/installation/issues/157

## What
Unable to run uninstall playbook from Mac

## Why
Uninstall playbook requires <https://stedolan.github.io/jq/> and will install it. The installation needs to be done by brew when it is a Mac, 

## How
- Check if is Mac and perform properly the installation
- Ignore tasks which will install it on Linux SO

## Verification Steps

Execute the uninstall script from a mac. The issue will be faced when it starts and it is not required to have an installation at all since this tasks are performed in the localhost. 

## Checklist:

- [X] Code has been tested locally by PR requester
- [ ] Changes have been successfully verified by another team member

## Progress

- [x] Finished task
- [ ] TODO

## Additional Notes

Test performed locally many times from a MacOX. *IMPORTANT*: The test was performed from "bastion"/RHDS too.

```
$ ansible-playbook -i inventories/hosts playbooks/uninstall.yml

PLAY [localhost] *******************************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************************
ok: [127.0.0.1]

TASK [Check that the jq exists] ****************************************************************************************************************************
skipping: [127.0.0.1]

TASK [download jq] *****************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [brew install jq] *************************************************************************************************************************************
changed: [127.0.0.1]

TASK [Get namespaces to clean up] **************************************************************************************************************************
changed: [127.0.0.1]

TASK [Delete namespaces] ***********************************************************************************************************************************

TASK [Uninstall launcher] **********************************************************************************************************************************

TASK [launcher : Delete Launcher oauthclient] **************************************************************************************************************
ok: [127.0.0.1]

TASK [launcher : Delete project namespace: launcher] *******************************************************************************************************
ok: [127.0.0.1]

TASK [Uninstall che] ***************************************************************************************************************************************

TASK [che : Set initial vars] ******************************************************************************************************************************
ok: [127.0.0.1]

TASK [che : Delete objects labeled as app:che] *************************************************************************************************************
ok: [127.0.0.1] => (item=che)
ok: [127.0.0.1] => (item=keycloak)
ok: [127.0.0.1] => (item=postgres)

TASK [che : Retrieve service account secrets] **************************************************************************************************************
changed: [127.0.0.1]

TASK [che : Delete service account secrets] ****************************************************************************************************************
skipping: [127.0.0.1] => (item=) 

TASK [che : Deleting remaining resources] ******************************************************************************************************************
ok: [127.0.0.1] => (item=[u'che', u'serviceaccount'])
ok: [127.0.0.1] => (item=[u'che', u'rolebinding'])
ok: [127.0.0.1] => (item=[u'che', u'pvc'])
ok: [127.0.0.1] => (item=[u'postgres', u'serviceaccount'])
ok: [127.0.0.1] => (item=[u'postgres', u'rolebinding'])
ok: [127.0.0.1] => (item=[u'postgres', u'pvc'])
ok: [127.0.0.1] => (item=[u'keycloak', u'serviceaccount'])
ok: [127.0.0.1] => (item=[u'keycloak', u'rolebinding'])
ok: [127.0.0.1] => (item=[u'keycloak', u'pvc'])

TASK [che : Delete che namespace] **************************************************************************************************************************
ok: [127.0.0.1]

TASK [che : Generate keycloak auth token for admin user] ***************************************************************************************************
skipping: [127.0.0.1]

TASK [che : Delete client che-client from realm] ***********************************************************************************************************
skipping: [127.0.0.1]

TASK [Uninstall managed services broker] *******************************************************************************************************************

TASK [msbroker : Delete managed service broker resources in managed-service-broker] ************************************************************************
changed: [127.0.0.1]

TASK [msbroker : Delete project namespace: managed-service-broker] *****************************************************************************************
changed: [127.0.0.1]

TASK [msbroker : Delete CRDs] ******************************************************************************************************************************
changed: [127.0.0.1] => (item=https://raw.githubusercontent.com/integr8ly/syndesis/master/install/operator/deploy/syndesis-crd.yml)

TASK [Uninstall 3scale] ************************************************************************************************************************************

TASK [3scale : Delete project namespace: 3scale] ***********************************************************************************************************
ok: [127.0.0.1]

TASK [Uninstall Gitea] *************************************************************************************************************************************

TASK [gitea : Delete project namespace: gitea] *************************************************************************************************************
ok: [127.0.0.1]

TASK [gitea : Check if webapp is available] ****************************************************************************************************************
changed: [127.0.0.1]

TASK [gitea : Delete Gitea token env var from the webapp] **************************************************************************************************
skipping: [127.0.0.1]

TASK [Delete enmasse cluster service broker] ***************************************************************************************************************
changed: [127.0.0.1]

TASK [Delete project namespace: enmasse] *******************************************************************************************************************
ok: [127.0.0.1]

TASK [Uninstall the webapp] ********************************************************************************************************************************

TASK [webapp : Remove OpenShift OAuth client] **************************************************************************************************************
ok: [127.0.0.1]

TASK [webapp : Remove webapp namespace webapp] *************************************************************************************************************
ok: [127.0.0.1]

TASK [Uninstall rhsso] *************************************************************************************************************************************

TASK [rhsso : Delete keycloak realm] ***********************************************************************************************************************
ok: [127.0.0.1]

TASK [rhsso : Delete keycloak realm] ***********************************************************************************************************************
ok: [127.0.0.1]

TASK [rhsso : Wait for keycloak resources to be removed] ***************************************************************************************************
ok: [127.0.0.1]

TASK [rhsso : Wait for keycloakrealms to be removed] *******************************************************************************************************
ok: [127.0.0.1]

TASK [rhsso : Delete project namespace: sso] ***************************************************************************************************************
ok: [127.0.0.1]

TASK [rhsso : Get all users created by rhsso] **************************************************************************************************************
changed: [127.0.0.1]

TASK [rhsso : Delete users] ********************************************************************************************************************************
skipping: [127.0.0.1]

TASK [rhsso : Get RHSSO Identities] ************************************************************************************************************************
changed: [127.0.0.1]

TASK [rhsso : Delete user identities] **********************************************************************************************************************
skipping: [127.0.0.1]

TASK [Uninstall Nexus] *************************************************************************************************************************************

TASK [nexus : Delete nexus namespace] **********************************************************************************************************************
ok: [127.0.0.1]

TASK [Uninstall Fuse] **************************************************************************************************************************************

TASK [fuse : Generate fuse operator image stream template] *************************************************************************************************
ok: [127.0.0.1]

TASK [fuse : Delete Fuse image streams] ********************************************************************************************************************
ok: [127.0.0.1] => (item=/tmp/fuse-operator.yml)
ok: [127.0.0.1] => (item=https://raw.githubusercontent.com/syndesisio/fuse-online-install/1.4.8/resources/fuse-online-image-streams.yml)
ok: [127.0.0.1] => (item=https://raw.githubusercontent.com/jboss-fuse/application-templates/application-templates-2.1.fuse-710017-redhat-00006/fis-image-streams.json)

TASK [fuse : Delete Fuse quickstart templates] *************************************************************************************************************
changed: [127.0.0.1] => (item=eap-camel-amq-template.json)
changed: [127.0.0.1] => (item=eap-camel-cdi-template.json)
changed: [127.0.0.1] => (item=eap-camel-cxf-jaxrs-template.json)
changed: [127.0.0.1] => (item=eap-camel-cxf-jaxws-template.json)
changed: [127.0.0.1] => (item=eap-camel-jpa-template.json)
changed: [127.0.0.1] => (item=karaf-camel-amq-template.json)
changed: [127.0.0.1] => (item=karaf-camel-log-template.json)
changed: [127.0.0.1] => (item=karaf-camel-rest-sql-template.json)
changed: [127.0.0.1] => (item=karaf-cxf-rest-template.json)
changed: [127.0.0.1] => (item=spring-boot-camel-amq-template.json)
changed: [127.0.0.1] => (item=spring-boot-camel-config-template.json)
changed: [127.0.0.1] => (item=spring-boot-camel-drools-template.json)
changed: [127.0.0.1] => (item=spring-boot-camel-infinispan-template.json)
changed: [127.0.0.1] => (item=spring-boot-camel-rest-sql-template.json)
changed: [127.0.0.1] => (item=spring-boot-camel-teiid-template.json)
changed: [127.0.0.1] => (item=spring-boot-camel-template.json)
changed: [127.0.0.1] => (item=spring-boot-camel-xa-template.json)
changed: [127.0.0.1] => (item=spring-boot-camel-xml-template.json)
changed: [127.0.0.1] => (item=spring-boot-cxf-jaxrs-template.json)
changed: [127.0.0.1] => (item=spring-boot-cxf-jaxws-template.json)

TASK [fuse : Delete Fuse Console templates] ****************************************************************************************************************
changed: [127.0.0.1] => (item=fis-console-cluster-template.json)
changed: [127.0.0.1] => (item=fis-console-namespace-template.json)

PLAY [master] **********************************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************************
ok: [master.cmacedo-b415.openshiftworkshop.com]

TASK [Uninstall rhsso] *************************************************************************************************************************************

TASK [rhsso : Check master-config has been modified by the installer] **************************************************************************************
changed: [master.cmacedo-b415.openshiftworkshop.com]

TASK [rhsso : Remove RH-SSO identity provider from master config] ******************************************************************************************
skipping: [master.cmacedo-b415.openshiftworkshop.com]

TASK [rhsso : Read master-config to check] *****************************************************************************************************************
skipping: [master.cmacedo-b415.openshiftworkshop.com]

TASK [rhsso : Add htpasswd identity provider to master config] *********************************************************************************************
skipping: [master.cmacedo-b415.openshiftworkshop.com]

TASK [rhsso : Restart master api] **************************************************************************************************************************
skipping: [master.cmacedo-b415.openshiftworkshop.com]

TASK [rhsso : Restart master controllers] ******************************************************************************************************************
skipping: [master.cmacedo-b415.openshiftworkshop.com]

PLAY RECAP *************************************************************************************************************************************************
127.0.0.1                  : ok=32   changed=12   unreachable=0    failed=0   
master.cmacedo-b415.openshiftworkshop.com : ok=2    changed=1    unreachable=0    failed=0   
```

### CODE REVIEW

**Comment by camilamacedo86** [comment]
@austincunningham thank you. The test was indeed also performed from bastion.

**Comment by austincunningham** [comment]
@camilamacedo86 Weird running the ansible playbook from the bastion host shouldn't be effected by your local environment

**Comment by camilamacedo86** [comment]
Hi @philbrookes,

Could you help me with this one?

**Comment by camilamacedo86** [comment]
Closing since it was not merged and is opened for too long and probably outdated.

**Pull request closed without merging**
