### PR TITLE
Add back the creation of wt2 routes.

### PR DESCRIPTION
**Pull request by mikenairn**
* Adds back the creation of the wt2 routes for each user, was removed as part of https://github.com/integr8ly/installation/pull/121

### CODE REVIEW

**Comment by mikenairn** [comment]
@david-martin @pmccarthy Do we also need to revert the amp prefix on the threescale_route_suffix? I'm assuming we do, and remove  wildcardPolicy: "Subdomain" form the CR. This would bring it back to working as it was before https://github.com/integr8ly/installation/pull/114

**Comment by pmccarthy** [comment]
@aidenkeating FYI ^^

**Comment by pmccarthy** [comment]
@mikenairn Looks like we also remove that amp prefix as part of https://github.com/integr8ly/installation/pull/118/files

**Comment by david-martin** [comment]
> Do we also need to revert the amp prefix on the threescale_route_suffix

Yes, as the webapp shows the incorrect route url.

`https://wt2-evals-example-com-3scale.amp.apps.mnairn-65f8.openshiftworkshop.com` instead of
`https://wt2-evals-example-com-3scale.apps.mnairn-65f8.openshiftworkshop.com`

This is based on a placeholder of `https://wt2-{user-sanitized-username}-3scale.{openshift-app-host}` in the webapp

**Comment by mikenairn** [comment]
@david-martin @pmccarthy Yep, reverted that all now also. Re-creating that entire integreatly install from scratch now to verify.

**Comment by david-martin** [comment]
@mikenairn Webapp is showing the correct url now

> Enter https://wt2-evals-example-com-3scale.apps.mnairn-65f8.openshiftworkshop.com in the Staging Public Base URL. Note that this route should point to the shared staging APIcast in the 3scale .....

**Pull request merged**
