### PR TITLE
Add custom SOP URLs to enmasse alerts; Fix alertmanager slack vars

### PR DESCRIPTION
**Pull request by grdryn**
JIRA:
https://issues.redhat.com/browse/INTLY-8385
https://issues.redhat.com/browse/INTLY-8386

This is a cherry-pick of #1369.

Upgrade log from release-1.6.1: https://gist.github.com/grdryn/ec1576e610bc51b7f578a7fc91b4028b

### CODE REVIEW

**Comment by grdryn** [comment]
image


Someone should delete the `1.7` branch...it looks old and unrelated to v1.7 and is confusing as h*ck.

**Comment by grdryn** [comment]
> image
> 
> Someone should delete the `1.7` branch...it looks old and unrelated to v1.7 and is confusing as h*ck.

...

image

@maleck13 Even though it says it was last "updated" by you, I guess that doesn't mean that you had anything to do with it. In any case, I have deleted that branch now. It was listed under "stale branches" and I expect it's no longer needed.

**Comment by david-martin** [comment]
/approve
Thanks @grdryn

**Comment by grdryn** [comment]
This seems to have been merged now, even though the PR doesn't reflect that for some reason. It might be because I originally opened it targetting the `1.7` branch, and then moved it to `v1.7` here in the GH web UI. I'm not sure though. I'll close this now in any case.

**Pull request closed without merging**
