### PR TITLE
Remove prometheus alerts which defined as unnecessary.

### PR DESCRIPTION
**Pull request by camilamacedo86**
## Motivation
- https://issues.jboss.org/browse/AEROGEAR-9647
- https://issues.jboss.org/browse/AEROGEAR-9645
- https://issues.jboss.org/browse/AEROGEAR-9646
## What 
-  Remove UnifiedPushPodCount
-  MobileSecurityServicePodCount
-  MobileDeveloperConsolePodCount

## Why
These alerts were defined as unnecessary.

### CODE REVIEW

**Comment by camilamacedo86** [comment]
Hi @wei-lee @grdryn @laurafitzgerald,

Please, could you check this small one?

**Comment by laurafitzgerald** [comment]
@camilamacedo86 the change looks fine to me. I will do verification soon. Need to get an environment.

**Comment by laurafitzgerald** [comment]
Verifying this now.

**Comment by laurafitzgerald** [comment]
@camilamacedo86 It's not part of this change, but the name of the prometheus rule for MSS is less specific than the others. Could we update it? https://github.com/integr8ly/installation/pull/785/files#diff-938401e345a3a2a24a45c0c3703c1981R9

**Comment by laurafitzgerald** [comment]
I think it needs approval by a code owner. @odra I've verified the changes are working correctly. I have one small feedback item but will leave it up to @camilamacedo86 about making this name change.

**Pull request merged**
