### PR TITLE
Update the web-app and web-app-operator verson

### PR DESCRIPTION
**Pull request by STEPHINRACHEL**
## Additional Information
Version bump for web-app to 2.28.1 and web-app-operator to v0.0.63

## Verification Steps
As the verifier of the PR the following process should be done:

### Installation Verification
- Ensure the author of the PR has attached a log of the installation run from his branch to the jira or pr and check that it exited as expected.
- Verify the fresh installation is correct on cluster provided by PR author 
### Upgrade Verification
- After installation verification, notify the PR author to begin an upgrade on their cluster
- Ensure the developer of the PR has attached a log of the upgrade run from his branch to the jira or pr and check that it exited as expected. 
- If possible, look at the tasks that ran and see they match the PR
- Verify the upgrade is correct on cluster provided by PR author 

## Checklist

- [ ] Updated [Changelog](https://github.com/integr8ly/installation/blob/master/CHANGELOG.md)
- [ ] Tested Installation
- [ ] Tested Uninstallation
- [ ] Tested or Created follow on for Upgrade

Is an upgrade task required and are there additional steps needed to test this?
- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by pb82** [comment]
Looks good, but we also need to make sure upgrading from the previous version works (when running the upgrade playbook)

**Comment by pb82** [comment]
@STEPHINRACHEL this looks good although we probably don't need all of the upgrade steps. Have you tried running the upgrade from 1.9.0?

**Comment by STEPHINRACHEL** [comment]
@pb82 Tested the upgrade from 1.9.0-rc2 it worked fine.

**Review by pb82 — APPROVED** [review]

**Pull request merged**
