### PR TITLE
update release tag

### PR DESCRIPTION
**Pull request by philbrookes**

### CODE REVIEW

**Comment by mikenairn** [comment]
@philbrookes Is this a cherry-pick from master?

**Comment by philbrookes** [comment]
no, I thought master was supposed to point at master? This is just for the 1.3 branch

**Comment by trepel** [comment]
We didn't really have a discussion about 'master pointing to master' yet. For now master just does not point to master so this can go to 'master' branch as well

**Comment by maleck13** [comment]
releases are cut from master and so the version on master should be the latest stable version

**Comment by maleck13** [comment]
verified on Phil's cluster

**Pull request merged**
