### PR TITLE
adding code to save api keys prior to am config deletion

### PR DESCRIPTION
**Pull request by sclarkso**
## Additional Information
https://issues.redhat.com/browse/INTLY-9132

## Verification Steps
I have not tested this, this pr is to work out the changes.

### Installation Verification
Not done.
### Upgrade Verification
Not done.

## Checklist

- [ ] Updated [Changelog](https://github.com/integr8ly/installation/blob/master/CHANGELOG.md)
- [ ] Tested Installation
- [ ] Tested Uninstallation
- [ ] Tested or Created follow on for Upgrade

Is an upgrade task required and are there additional steps needed to test this?
- [x] Yes
- [ ] No

### CODE REVIEW

**Comment by Rajagopalan-Ranganathan** [comment]
@sclarkso The changes look fine to me. But I am not aware of 1.X , so can you test these changes install and upgrade path in 1.X and share the results in the PR so that i can approve the changes?

**Comment by Nanyte25** [comment]
@sclarkso can you test this PR on a cluster and share your result so we can get this merged?

**Comment by sclarkso** [comment]
@Rajagopalan-Ranganathan Is there a sop or howto on how to test ansible changes in an upgrade?  Mark told me use rhpds, which makes sense, so I can spin up an rhpds cluster and install rhmi 1, i'm just not sure how then to test an upgrade using changes that are in a PR?

**Comment by Rajagopalan-Ranganathan** [comment]
> @Rajagopalan-Ranganathan Is there a sop or howto on how to test ansible changes in an upgrade? Mark told me use rhpds, which makes sense, so I can spin up an rhpds cluster and install rhmi 1, i'm just not sure how then to test an upgrade using changes that are in a PR?

@sclarkso : I got this information from another team member: You should SSH into a master node.  (mostly there might be only one master node).  then cloning the repo, checking out the branch (PR  branch). Run the upgrade playbook. ``` ansible-playbook -i inventories/pds.template playbooks/upgrade.yml``` hopefully that should do it.

**Pull request closed without merging**
