### PR TITLE
fix: Updating code owners

### PR DESCRIPTION
**Pull request by davidffrench**
## Additional Information
Reducing the number of code owners

### CODE REVIEW

**Comment by davidffrench** [comment]
@maleck13 @david-martin Looking for your input here on who you think should be code owners?

**Comment by david-martin** [comment]
This will reduce the amount to people that get mails for every PR, but also put the onus on the right people to ensure PRs have all due consideration before merging. 👍

**Comment by davidffrench** [comment]
Thanks @david-martin . Do you think it is the right people? Is there anyone you can think of that I am missing?

**Comment by david-martin** [comment]
@davidffrench Sure. If we find someone else needs owner rights, we'll discuss then.

**Comment by davidffrench** [comment]
Thanks @david-martin

**Pull request merged**
