### PR TITLE
Add playbook for 1.4.0 upgrade

### PR DESCRIPTION
**Pull request by aidenkeating**
Add a playbook that bumps the MSB and Solution Explorer versions.

I'm going to give this a fresh run to ensure everything works as expected.

### CODE REVIEW

**Comment by aidenkeating** [comment]
@maleck13 @philbrookes Mind taking a look?

@philbrookes I think this covers what is left after your PR in #553 . I can include a manifest secret update if we want to do that also?

**Comment by trepel** [comment]
@aidenkeating just a question. This seems to be 1.3.0 -> 1.4.0 specific, why to merge to master then?

**Comment by aidenkeating** [comment]
@trepel From what I'm aware 1.4 won't be cut and cherry-picked from a 1.3 tag/branch and there currently isn't a 1.4 branch. So I was just following the example of #553

**Comment by pb82** [comment]
👀

**Comment by aidenkeating** [comment]
@pb82 Thanks for the verification, I've rebased on top of the merged SSO changes. Mind taking one more look?

**Comment by pb82** [comment]
@aidenkeating Ok, retrying now

**Comment by pb82** [comment]
@aidenkeating when i try to run `playbooks/upgrades/upgrade.yaml` i get this error:

```
TASK [Update keycloak-operator image tag] **************************************************************************************************************************************************************************************************************************************
fatal: [127.0.0.1]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'upgrade_sso_operator_image' is undefined\n\nThe error appears to have been in '/root/installation/playbooks/upgrades/upgrade.yaml': line 23, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n    # SSO\n    - name: Update keycloak-operator image tag\n      ^ here\n"}
```

**Pull request merged**
