### PR TITLE
INTLY-6950: Update enmasse version to 1.4.1.GA

### PR DESCRIPTION
**Pull request by JameelB**
## Additional Information
Original PR: https://github.com/integr8ly/installation/pull/1322
Related JIRA: https://issues.redhat.com/browse/INTLY-6950

### Installation Verification
Installation Logs: https://gist.github.com/JameelB/70529e44e3df620c0ff9dd933247f1d8

Post install verification:
- Verify correct version is used by the enmasse console: 0.31.1.rc1-redhat-00001
- Verify no alerts are firing on prometheus & alert manager
- Verify enmasse grafana dashboards created

### CODE REVIEW

**Comment by JameelB** [comment]
@pawelpaszki This needs to land on 1.7, can you test this on OSD when you get the time please?

**Comment by pawelpaszki** [comment]
@JameelB - gonna trigger uninstallation on one of the osd clusters and then will install with this PR

**Pull request merged**
