### PR TITLE
ignore errors if no fuse deployment is triggered

### PR DESCRIPTION
**Pull request by wei-lee**
## Additional Information
https://issues.redhat.com/browse/INTLY-4733

## Verification Steps

Run the upgrade job twice. Both should finish successfully. 

- [ ] Tested Installation
- [ ] Tested Uninstallation
- [x] Tested or Created follow on for Upgrade

### CODE REVIEW

**Comment by wei-lee** [comment]
@jhellar if you can help verify the issue, we can then get it merged before cutting next RC. Thanks.

**Comment by jhellar** [comment]
looking at it now

**Comment by jhellar** [comment]
Verified it on RHPDS cluster - second run of upgrade playbook passed.

**Pull request merged**
