### PR TITLE
Delete evals directory

### PR DESCRIPTION
**Pull request by pmccarthy**
## Additional Information
Removing evals directory and storing all of its content in the root of the repository instead

## Verification Steps
- Execute an install
- Validate updated README steps

### CODE REVIEW

**Comment by pmccarthy** [comment]
Updated version of https://github.com/integr8ly/installation/pull/353

**Comment by pmccarthy** [comment]
@maleck13 @mikenairn Ideally we could get this merged back ASAP to avoid conflicts etc.

**Comment by mikenairn** [comment]
@pmccarthy Fine with me, but this will break quite a few Jenkins jobs. Let me check how many and if we can update them beforehand to deal with the change.

**Comment by maleck13** [comment]
+1 to fixing jobs at the same time

**Comment by pmccarthy** [comment]
@maleck13 @mikenairn Looks like we've hit conflicts already. Maybe if we look at getting PRs in to fix CI/CD jobs first, I'll then issue a new PR and we merge as quickly as possible. Having to resolve conflicts on an existing PR will be a real pain.

**Comment by mikenairn** [comment]
@pmccarthy I have a PR for the Jenkins jobs here https://github.com/integr8ly/ci-cd/pull/71, just want @tremes and/or @trepel to take a look and make sure they are happy enough with it before i update any running jobs.

**Comment by mikenairn** [comment]
@pmccarthy The CI/CD PR has been merged now, so jobs should hopefully handle this change.

**Comment by pmccarthy** [comment]
Closing as this has been merged in a separate PR: https://github.com/integr8ly/installation/pull/451

**Pull request closed without merging**
