### PR TITLE
add current sheriff eng to owners

### PR DESCRIPTION
**Pull request by aidenkeating**
add current support sheriffs to owners to allow for upgrade work to progress

### CODE REVIEW

**Comment by aidenkeating** [comment]
@david-martin mind taking a look?

**Comment by david-martin** [comment]
@aidenkeating I'm going to put this on hold, pending a discussion with @maleck13 .

If we added sheriff as owners, that would mean everyone gets added as rotation happens. The slippery slope argument here why not just add everyone now (and that goes against the idea of a small set of owners :) )

**Comment by maleck13** [comment]
agree @david-martin the idea was to keep a small set of owners to try and help with quality on reviews. If stuff is not getting reviewed merged we need to address that though

**Comment by aidenkeating** [comment]
@maleck13 @david-martin That makes sense to me, the pattern we've appeared to be following so far is:

- Someone from the sheriff team produces a PR
- Someone else from the sheriff team does a verification and review
- Someone from the owners file is asked for a final review

If we're happy with that, and it's not expected that the owners will need to perform the verification again, I'm happy to close this

**Pull request closed without merging**
