### PR TITLE
INTLY-4649 Allow traffic from middleware namespaces

### PR DESCRIPTION
**Pull request by sergioifg94**
## Description
Add a step to the installation to modify the default project template adding
a new `allow-from-middleware-namespaces` NetworkPolicy. This policy allows
traffic from namespaces with the `integreatly-middleware-service` label.

This way we ensure that newly created projects in the cluster are accessible by
default from the Integreatly products.

## Additional Information
[Link to JIRA](https://issues.redhat.com/browse/INTLY-4649)
[Link to bug solved by this PR](https://issues.redhat.com/browse/INTLY-7070)

## Verification Steps

> Already tested on RHPDS cluster

As the verifier of the PR the following process should be done:

### Installation Verification
Locate the default project template (called `project-request` in `default` namespace) in your cluster and perform an installation for each of the following scenarios:

| # |  Scenario | Excepted outcome |
| - | -----------  | ------------------------- |
| 1 | The template has no `NetworkPolicy` objects | The template is not altered after installation |
| 2* | The template has at least one `NetworkPolicy` that's not called `allow-from-middleware-namespaces` | A NetworkPolicy is appended to the template with the name `allow-from-middleware-namespaces` |
| 3 | The template has at least one `NetworkPolicy` that includes the `allow-from-middleware-namespaces` one | The template is not altered after installation |

\* For scenario `#2`, create a new project in the cluster after installation and verify that:

1. The `allow-from-middleware-namespaces` NetworkPolicy has been created
2. A container from the `openshift-3scale` namespace is able to access services in the newly created project.

## Checklist

- [ ] Updated [Changelog](https://github.com/integr8ly/installation/blob/master/CHANGELOG.md)
- [ ] Tested Installation
- [ ] Tested Uninstallation
- [ ] Tested or Created follow on for Upgrade

Is an upgrade task required and are there additional steps needed to test this?
- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by laurafitzgerald** [comment]
👀  I'm reviewing this now.

**Comment by laurafitzgerald** [comment]
Chatted to @sergioifg94 about this one. He tested that manually adding the NetworkPolicy fixes the issue and has done an install on PDS to verify the ansible changes works. Is that sufficient for verification of this change?

**Comment by laurafitzgerald** [comment]
@jessesarn I've reviewed the code and am happy with the ansible code. Please see my comment above about verification. I don't have access to `/approve` or `/lgtm`. If you are happy with the aboe could you add those to this pr.

**Comment by jessesarn** [comment]
@laurafitzgerald I would have thought you would be able to use /lgtm, but happy to help push this thru.
/lgtm
/approve

**Pull request merged**
