### PR TITLE
webapp uninstall cors data

### PR DESCRIPTION
**Pull request by odra**
Removes webapp cors data from master config file when running the uninstall playbook.

## Verification

Install integreatly:

```
ansible-playbook -i inventories/host playbooks/install.yml
```

SSH into the master node and check if the webapp cors info is there (searching for "web" in enough).

Now run the uninstall playbook:

```
ansible-playbook -i inventories/host playbooks/uninstall.yml
```

The master config file again and the previously added webapp cors data should not be there.

### CODE REVIEW

**Comment by trepel** [comment]
@odra Reviewing

**Comment by odra** [comment]
Sounds good, I will add the check and ask for a review again once it is done.

**Comment by odra** [comment]
@trepel mind reviewing it again?

**Comment by trepel** [comment]
@odra looking at it now

**Pull request merged**
