### PR TITLE
disable enmasse own monitoring as it breaks application monitoring stack install

### PR DESCRIPTION
**Pull request by austincunningham**
## Verification Steps
As the verifier of the PR the following process should be done:

### Installation Verification
- Ensure the author of the PR has attached a log of the installation run from his branch to the jira or pr and check that it exited as expected.
- Verify the fresh installation is correct on cluster provided by PR author 
### Upgrade Verification
- After installation verification, notify the PR author to begin an upgrade on their cluster
- Ensure the developer of the PR has attached a log of the upgrade run from his branch to the jira or pr and check that it exited as expected. 
- If possible, look at the tasks that ran and see they match the PR
- Verify the upgrade is correct on cluster provided by PR author 

## Checklist

- [ ] Updated [Changelog](https://github.com/integr8ly/installation/blob/master/CHANGELOG.md)
- [ ] Tested Installation
- [ ] Tested Uninstallation
- [ ] Tested or Created follow on for Upgrade

Is an upgrade task required and are there additional steps needed to test this?
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by matskiv** [comment]
This needs to be tested with #1283 right?
We could change this PR to target `amq-online-ga` branch instead of master.

**Comment by jessesarn** [comment]
Does somebody have install/upgrade logs already?

**Comment by matskiv** [comment]
@jessesarn I don't. I haven't ran this. I was expecting we would just merge this to `amq-online-ga` branch, and then verify PR from `amq-online-ga` to `master`

**Comment by jessesarn** [comment]
Good point.  Since its going to the amq-online-ga branch first, for further testing, I see no problem with merging.
/approve

**Pull request merged**
