### PR TITLE
install codeready using the cli tool

### PR DESCRIPTION
**Pull request by wei-lee**
## Additional Information
https://issues.redhat.com/browse/INTLY-5336

## Verification Steps
As the verifier of the PR the following process should be done:

### Installation Verification
- Provision an OpenShift 3.x cluster
- Run the installation playbook. Wait until Codeready is installed.
- Login to Codeready and create a workspace. It should work.

### CODE REVIEW

**Comment by wei-lee** [comment]
@damienomurchu can you try this branch for the pipeline? it should fix the issue you are having.

**Comment by damienomurchu** [comment]
@wei-lee just seeing this now - will try pds install from this branch and see if it resolves issue

**Comment by damienomurchu** [comment]
@wei-lee - verifying changes resolved issue when run against a pds cluster.

Do you we need upgrade logic in this PR?

**Comment by wei-lee** [comment]
@damienomurchu upgrade is done in a different PR: https://github.com/integr8ly/installation/pull/1112 which is already merged.

**Comment by pb82** [comment]
@damienomurchu upgrade logic was already verified, i'm also currently running an installation from this branch.

**Pull request merged**
