### PR TITLE
INTLY-7479

### PR DESCRIPTION
**Pull request by laurafitzgerald**
## Additional Information
https://issues.redhat.com/browse/INTLY-7479

### Installation Verification
No Installation changes - no verification required.
### Upgrade Verification
Release 1.6.1 install [logs](https://gist.github.com/laurafitzgerald/d24102f2c50e85752bbbe5ae7f709bb4)
Prometheus Rule pre upgrade:
Screenshot 2020-05-07 at 16 26 11
Upgrade on this branch [logs](https://gist.github.com/laurafitzgerald/c9701a15fb776660de7f98bf82b323ee#file-intly-7479-upgrade-L371-L384)
Prometheus Rule post upgrade:
Screenshot 2020-05-07 at 16 36 49
Prometheus Alert post upgrade
Screenshot 2020-05-07 at 16 39 15

## Checklist

- [ ] Updated [Changelog](https://github.com/integr8ly/installation/blob/master/CHANGELOG.md)
- [ ] Tested Installation
- [ ] Tested Uninstallation
- [x] Tested or Created follow on for Upgrade

Is an upgrade task required and are there additional steps needed to test this?
- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by JameelB** [comment]
/lgtm

Code changes looks good. Installation and upgrade logs looks as expected.

/assign @pawelpaszki to test on osd

**Comment by pawelpaszki** [comment]
Verified when upgrading from 1.6.1 to this feature branch on OSD:

Screenshot 2020-05-08 at 06 35 36

**Pull request merged**
