### PR TITLE
INTLY-7382 Update 'launcher_catalog_git_ref' from 1.6.0 to 1.7.0 in manifest file

### PR DESCRIPTION
**Pull request by trdoyle81**
## Additional Information
Update 'launcher_catalog_git_ref' from 1.6.0 to 1.7.0 in manifest file
https://issues.redhat.com/browse/INTLY-7382
See related PR:
https://github.com/integr8ly/launcher-booster-catalog/pull/12

OSD Verification:
Installation Logs: https://qe-tower.rhmw.io/#/jobs/playbook/2963

Post install verification:
Launcher now displays the correct version of Fuse:
image

### CODE REVIEW

**Comment by trdoyle81** [comment]
@JameelB

**Comment by trdoyle81** [comment]
@JameelB

**Comment by trdoyle81** [comment]
@JameelB

**Comment by JameelB** [comment]
/hold

Holding this pr until it's verified on osd

**Pull request merged**
