### PR TITLE
INTLY-9516 Update timeouts

### PR DESCRIPTION
**Pull request by CathalOConnorRH**
## Additional Information
https://issues.redhat.com/browse/INTLY-9516

### CODE REVIEW

**Comment by CathalOConnorRH** [comment]
@jessesarn Can you review this when you get a chance please

**Comment by jessesarn** [comment]
:eyes:

**Comment by jessesarn** [comment]
Works perfectly
Install log: https://gist.github.com/jessesarn/ede0420b0f3c6266c795538a96caa746

**Pull request merged**
