### PR TITLE
[WIP] middleware-monitoring update

### PR DESCRIPTION
**Pull request by fh-automatron**
Created automatically by jenkins

### CODE REVIEW

**Comment by mikenairn** [comment]
/cc @david-martin @pb82

Might be worth looking into how we can select reviewers/approvers based on lines changed in that file

**Comment by david-martin** [comment]
> Might be worth looking into how we can select reviewers/approvers based on lines changed in that file

Is that possible via openshift-ci-robot or github codeowners?

**Comment by mikenairn** [comment]
@david-martin Was more a note to myself. It is possible to add OWNERS for different directories with both (prow OWNERS and GH CODEOWNERS), but not sure about actually checking what's changed in an individual file, probably not.

**Comment by david-martin** [comment]
This has already been verified on the 1.5 stream in https://github.com/integr8ly/installation/pull/1073

@pb82  Any concerns with merging this to master?

**Comment by pb82** [comment]
@david-martin No, it looks like the main change in 0.0.27 is this: https://github.com/integr8ly/application-monitoring-operator/commit/78284a4034ad0bc132bb722837c4320846c25ff4

There is also a later tag (0.0.28) but no release for it.

**Pull request closed without merging**
