### PR TITLE
Intly 2495 app metrics upgrade

### PR DESCRIPTION
**Pull request by odra**
## Verification Steps

**This is an upgrade only pr**

* Install integreatly from the following tag: `release-1.4.1`
* Run the `install_backups.yml` playbook from that same release
* Swicth to this branch
* Run the upgrade playbook adding the following var: `-e 'application_metrics=true'` 
* Check if the `application_monitoring` role was included and executed from the upgrade playbook

## Is an upgrade task required and are there additional steps needed to test this?

- [ ] Tested Installation
- [ ] Tested Uninstallation
- [ ] Tested or Created follow on for Upgrade

### CODE REVIEW

**Comment by laurafitzgerald** [comment]
👀

**Comment by aliok** [comment]
@laurafitzgerald @odra can we merge this one please? let's close the card https://trello.com/c/FBrIJ1GU/235-3-rhmi-metrics-install-as-a-developer-i-want-to-be-able-to-install-app-metrics-onto-an-rhmi-cluster-1

**Comment by odra** [comment]
I need a code owner approval to merge it

**Comment by laurafitzgerald** [comment]
agreed, merge merge merge! :)

**Pull request merged**
