### PR TITLE
Intly 2034

### PR DESCRIPTION
**Pull request by pb82**
Upgrade playbook for the 3scale postgres backup:

* adds the postgres version to the 3scale secret
* patches all cronjobs to use the latest image versino (1.0.2)

### CODE REVIEW

**Comment by odra** [comment]
backup image was not update in cronjob: image: quay.io/integreatly/backup-container:1.0.1

**Comment by pb82** [comment]
@odra was that one specific cronjob or all cronjobs?

**Comment by odra** [comment]
checked 3, all 3 are using the old one

**Comment by odra** [comment]
ran the following command:
 ansible-playbook -i inventories/hosts playbooks/upgrades/upgrade.yaml  -e 'backup_namespace=default'

**Pull request merged**
