### PR TITLE
INTLY-3909 Apply latest monitoring alerts during upgrade

### PR DESCRIPTION
**Pull request by david-martin**
## Additional Information
https://issues.jboss.org/browse/INTLY-3909

## Verification Steps

* install 1.5.1
* do an upgrade to 1.5.2 (this branch)
* verify the alert in the jira issue has been updated.

### Installation Verification
- Ensure the author of the PR has attached a log of the installation run from his branch to the jira or pr and check that it exited as expected.
- Verify the fresh installation is correct on cluster provided by PR author 
### Upgrade Verification
- After installation verification, notify the PR author to begin an upgrade on their cluster
- Ensure the developer of the PR has attached a log of the upgrade run from his branch to the jira or pr and check that it exited as expected. 
- If possible, look at the tasks that ran and see they match the PR
- Verify the upgrade is correct on cluster provided by PR author 

## Is an upgrade task required and are there additional steps needed to test this?

- [ ] Yes
- [ ] No

- [ ] Tested Installation
- [ ] Tested Uninstallation
- [ ] Tested or Created follow on for Upgrade

### CODE REVIEW

**Comment by trepel** [comment]
@david-martin I am verifying this on rhmi-qe1

**Comment by david-martin** [comment]
Upgrade logs https://gist.github.com/david-martin/f65fe5576d0d5768b81093409e5594de

**Comment by david-martin** [comment]
Updated CronJobsFailed alert expr

**Comment by trepel** [comment]
OSD rhmi-qe1 upgrade log:
https://tower.apps.integreatly-cicd.skunkhenry.com/#/jobs/playbook/33390

The CronJobsFailed alert updated as expected

**Comment by trepel** [comment]
@david-martin I guess some code owner needs to approve, correct?

**Pull request merged**
