### PR TITLE
V1.7 add missing rc2 changes

### PR DESCRIPTION
**Pull request by JameelB**
## Additional Information
Missing commits from the following PRS:
- https://github.com/integr8ly/installation/pull/1306
- https://github.com/integr8ly/installation/pull/1316
- https://github.com/integr8ly/installation/pull/1323
- https://github.com/integr8ly/installation/pull/1297

Verification:
- Ensure fuse installation completes successfully
- Ensure SSO version in manifest is `7.3.7.GA`
- Ensure apicurito installation completes successfully

### CODE REVIEW

**Comment by pawelpaszki** [comment]
verification completed as per steps in the description

**Comment by JameelB** [comment]
@jessesarn forgot to add myself in the 1.7 branch, can i get an approval here please? :)

**Pull request merged**
