### PR TITLE
Fuse dashboard imports

### PR DESCRIPTION
**Pull request by davidkirwan**
## Additional Information

JIRA: https://issues.jboss.org/browse/INTLY-602

*What*
Install the monitoring ‘addon’ CustomResources during integreatly installation.
https://github.com/syndesisio/syndesis/tree/22beae32f32fe42f3bb696f85ae5ef5acf938267/install/addons

*Why*
This will provide a number of Alerts & Dashboards that the Integreatly monitoring stack will detect and import.
These can be used to debug & diagnose Fuse issues

## Verification Steps
1. From the fork ``https://github.com/davidkirwan/intly-installation.git`` checkout branch ``fuse_dashboards`` on the openshift bastion/master instance.
2. Create the inventory with the master and key etc configured to point at the openshift master instance.
3. ``ansible-playbook -i inventories/hosts playbooks/install.yml -e eval_self_signed_certs=false`` Should run to completion successfully.
4. The port ``9090`` should also be exposed on the ``prometheus-service`` service.
5. application-monitoring-operator should be ``0.0.13`` in the ``middleware-monitoring`` namespace.
6. grafana operator should show importing of fuse dashboards successfully in its logs.
7. Visiting Grafana dashboard should show the fuse dashboards successfully (eventually).
8. ``ansible-playbook -i inventories/hosts playbooks/uninstall.yml -e eval_self_signed_certs=false`` should run to completion successfully.

## Is an upgrade task required and are there additional steps needed to test this?

- [x] Tested Installation
- [x] Tested Uninstallation
- [ ] Tested or Created follow on for Upgrade

### CODE REVIEW

**Comment by davidkirwan** [comment]
@pb82 https://github.com/integr8ly/application-monitoring-operator/pull/48 added change in there. Successfully ran the install/uninstall to completion on my own cluster, will retry once this linked is merged.

**Comment by david-martin** [comment]
@davidkirwan Leaving some notes from what we discovered yesterday:

* dashboards & alerts show up OK
* however, it doesn't look like any metrics are being scraped 
* this was tracked down to problem with the endpoint name in the ServiceMonitor not matching the endpoint name on the Pod (metrics vs. prometheus)

**Comment by david-martin** [comment]
On hold pending the output of https://github.com/syndesisio/syndesis/issues/5746 & comments in https://issues.jboss.org/browse/INTLY-602

**Comment by david-martin** [comment]
@davidkirwan It may be possible after https://github.com/syndesisio/syndesis/pull/5712 lands to tell the syndesis operator to install the monitoring addon. This would simplify the changes needed in the installer.
However, that PR is gargantuan ⚫️ so may take some time. Also, we'll rely on a new downstream release.

**Comment by davidkirwan** [comment]
Looks like will go with something similar to https://github.com/integr8ly/installation/pull/701 once the fuse online release goes live in the coming days/weeks.

**Pull request closed without merging**
