### PR TITLE
3scale update

### PR DESCRIPTION
**Pull request by fh-automatron**
Created automatically by jenkins

### CODE REVIEW

**Comment by obrienrobert** [comment]
Verified this upgrade on an RHPDS cluster using the following steps:
- Installed master (https://gist.github.com/obrienrobert/1b247e4afad5cc7765b23bfa19f4c76f)
- Completed WT2 successfully
- Upgraded using branch (https://gist.github.com/obrienrobert/528f9099503bea5fc204d596f61bffbd)
- Completed WT2 successfully

**Comment by philbrookes** [comment]
Did you confirm that the upgrade had taken place before retrying the walkthrough? How did you confirm that?

**Comment by obrienrobert** [comment]
@philbrookes In my last comment (https://github.com/integr8ly/installation/pull/1291#issuecomment-630259506) I've included both the install and upgrade logs. You can see from the manifest section of the logs that the 3scale version was updated. As this upgrade is a patch release (`2.8.0` -> `2.8.1`), the same image tag is being pulled: https://catalog.redhat.com/software/containers/detail/5d80bab8d70cc5521d516a4d

**Pull request merged**
