### PR TITLE
updating ups operator

### PR DESCRIPTION
**Pull request by secondsun**
## Additional Information
This PR updates the ups operator to the latest version.  This fixes a problem where unavailable enmasse resources were being cached.
## Verification Steps
UPS should install and be functional 

## Is an upgrade task required and are there additional steps needed to test this?
There are no extra steps

### CODE REVIEW

**Comment by secondsun** [comment]
I've been trying to verify this, but the installer fails when deploying 3scale.  I've rebased and am testing with the ga merged into master.

Here are the logs I'm seeing

```
Same problem, same place.  I've gtrabbed some logs from some pods this time that might help 
```
TASK [3scale : Verify 3Scale pods are running] ***********************************************************************************************************************************************************************************************
FAILED - RETRYING: Verify 3Scale pods are running (50 retries left).
FAILED - RETRYING: Verify 3Scale pods are running (49 retries left).
FAILED - RETRYING: Verify 3Scale pods are running (48 retries left).
FAILED - RETRYING: Verify 3Scale pods are running (47 retries left).
FAILED - RETRYING: Verify 3Scale pods are running (46 retries left).
FAILED - RETRYING: Verify 3Scale pods are running (45 retries left).
FAILED - RETRYING: Verify 3Scale pods are running (44 retries left).
FAILED - RETRYING: Verify 3Scale pods are running (43 retries left).
FAILED - RETRYING: Verify 3Scale pods are running (42 retries left).
FAILED - RETRYING: Verify 3Scale pods are running (41 retries left).
FAILED - RETRYING: Verify 3Scale pods are running (40 retries left).
FAILED - RETRYING: Verify 3Scale pods are running (39 retries left).
FAILED - RETRYING: Verify 3Scale pods are running (38 retries left).
FAILED - RETRYING: Verify 3Scale pods are running (37 retries left).
FAILED - RETRYING: Verify 3Scale pods are running (36 retries left).
FAILED - RETRYING: Verify 3Scale pods are running (35 retries left).
FAILED - RETRYING: Verify 3Scale pods are running (34 retries left).
FAILED - RETRYING: Verify 3Scale pods are running (33 retries left).
FAILED - RETRYING: Verify 3Scale pods are running (32 retries left).
FAILED - RETRYING: Verify 3Scale pods are running (31 retries left).
FAILED - RETRYING: Verify 3Scale pods are running (30 retries left).
FAILED - RETRYING: Verify 3Scale pods are running (29 retries left).
FAILED - RETRYING: Verify 3Scale pods are running (28 retries left).
FAILED - RETRYING: Verify 3Scale pods are running (27 retries left).
FAILED - RETRYING: Verify 3Scale pods are running (26 retries left).
FAILED - RETRYING: Verify 3Scale pods are running (25 retries left).
FAILED - RETRYING: Verify 3Scale pods are running (24 retries left).
FAILED - RETRYING: Verify 3Scale pods are running (23 retries left).
FAILED - RETRYING: Verify 3Scale pods are running (22 retries left).
FAILED - RETRYING: Verify 3Scale pods are running (21 retries left).
FAILED - RETRYING: Verify 3Scale pods are running (20 retries left).
FAILED - RETRYING: Verify 3Scale pods are running (19 retries left).
FAILED - RETRYING: Verify 3Scale pods are running (18 retries left).
FAILED - RETRYING: Verify 3Scale pods are running (17 retries left).
FAILED - RETRYING: Verify 3Scale pods are running (16 retries left).
FAILED - RETRYING: Verify 3Scale pods are running (15 retries left).
FAILED - RETRYING: Verify 3Scale pods are running (14 retries left).
FAILED - RETRYING: Verify 3Scale pods are running (13 retries left).
FAILED - RETRYING: Verify 3Scale pods are running (12 retries left).
FAILED - RETRYING: Verify 3Scale pods are running (11 retries left).
FAILED - RETRYING: Verify 3Scale pods are running (10 retries left).
FAILED - RETRYING: Verify 3Scale pods are running (9 retries left).
FAILED - RETRYING: Verify 3Scale pods are running (8 retries left).
FAILED - RETRYING: Verify 3Scale pods are running (7 retries left).
FAILED - RETRYING: Verify 3Scale pods are running (6 retries left).
FAILED - RETRYING: Verify 3Scale pods are running (5 retries left).
FAILED - RETRYING: Verify 3Scale pods are running (4 retries left).
FAILED - RETRYING: Verify 3Scale pods are running (3 retries left).
FAILED - RETRYING: Verify 3Scale pods are running (2 retries left).
FAILED - RETRYING: Verify 3Scale pods are running (1 retries left).
fatal: [127.0.0.1]: FAILED! => {"attempts": 50, "changed": false, "cmd": "oc get pods -o jsonpath='{.items[*].status.containerStatuses[?(@.ready==true)].ready}' -n 3scale | wc -w", "delta": "0:00:00.265330", "end": "2019-08-21 19:07:59.246321", "rc": 0, "start": "2019-08-21 19:07:58.980991", "stderr": "", "stderr_lines": [], "stdout": "14", "stdout_lines": ["14"]}

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************
127.0.0.1                  : ok=784  changed=397  unreachable=0    failed=1   
master.atlanta-f22d.example.opentlc.com : ok=7    changed=5    unreachable=0    failed=0   

[root@bastion 2 ~/installation master ↑·2|✔]# oc project 3scale
Now using project "3scale" on server "https://master.atlanta-f22d.example.opentlc.com:443".
[root@bastion 0 ~/installation master ↑·2|✔]# oc get pods
NAME                          READY     STATUS     RESTARTS   AGE
apicast-production-1-5cndd    0/1       Init:0/1   0          19m
apicast-production-1-deploy   1/1       Running    0          19m
apicast-staging-1-lhsvs       1/1       Running    0          19m
backend-cron-1-67qdk          1/1       Running    0          19m
backend-listener-1-deploy     0/1       Error      0          19m
backend-redis-1-skbqn         1/1       Running    0          19m
backend-worker-1-ddw6v        1/1       Running    0          19m
system-app-1-deploy           1/1       Running    0          19m
system-app-1-hook-pre         0/1       Error      8          19m
system-memcache-1-gmmqh       1/1       Running    0          19m
system-mysql-1-v6rgh          1/1       Running    0          19m
system-redis-1-g4vpn          1/1       Running    0          19m
system-sidekiq-1-deploy       1/1       Running    0          19m
system-sidekiq-1-fmvrb        0/1       Init:0/1   0          19m
system-sphinx-1-2hdqh         0/1       Init:0/1   0          19m
system-sphinx-1-deploy        1/1       Running    0          19m
zync-1-jntpn                  1/1       Running    0          19m
zync-database-1-82cfc         1/1       Running    0          19m
zync-que-1-4kgxm              1/1       Running    3          19m
[root@bastion 0 ~/installation master ↑·2|✔]# oc logs backend-listener-1-deploy
--> Scaling backend-listener-1 to 1
error: update acceptor rejected backend-listener-1: pods for rc '3scale/backend-listener-1' took longer than 600 seconds to become available
[root@bastion 0 ~/installation master ↑·2|✔]# oc logs system-app-1-hook-pre
ActiveMerchant MODE set to 'production'
No valid API key has been set, notifications will not be sent
[Core] Using http://backend-listener:3000/internal/ as URL
OpenIdAuthentication.store is nil. Using in-memory store.
[core] non-native log levels verbose, notice, critical emulated using UNKNOWN severity
rake aborted!
ThreeScale::Core::APIClient::ConnectionError: ThreeScale::Core::APIClient::ConnectionError: execution expired
/opt/system/vendor/bundle/ruby/2.4.0/gems/pisoni-1.26.0/lib/3scale/core/api_client/operations.rb:110:in `rescue in api_http'
/opt/system/vendor/bundle/ruby/2.4.0/gems/pisoni-1.26.0/lib/3scale/core/api_client/operations.rb:99:in `api_http'
/opt/system/vendor/bundle/ruby/2.4.0/gems/pisoni-1.26.0/lib/3scale/core/api_client/operations.rb:186:in `api'
/opt/system/lib/tasks/boot.rake:6:in `block (2 levels) in <top (required)>'
/opt/system/vendor/bundle/ruby/2.4.0/gems/bugsnag-6.11.1/lib/bugsnag/integrations/rake.rb:18:in `execute_with_bugsnag'
/opt/system/vendor/bundle/ruby/2.4.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `load'
/opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `kernel_load'
/opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:28:in `run'
/opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.17.3/lib/bundler/cli.rb:463:in `exec'
/opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.17.3/lib/bundler/cli.rb:27:in `dispatch'
/opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.17.3/lib/bundler/cli.rb:18:in `start'
/opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.17.3/exe/bundle:30:in `block in <top (required)>'
/opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.17.3/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.17.3/exe/bundle:22:in `<top (required)>'
/opt/rh/rh-ruby24/root/usr/local/bin/bundle:23:in `load'
/opt/rh/rh-ruby24/root/usr/local/bin/bundle:23:in `<main>'

Caused by:
Faraday::ConnectionFailed: execution expired
/opt/system/vendor/bundle/ruby/2.4.0/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:700:in `start'
/opt/system/vendor/bundle/ruby/2.4.0/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:631:in `connection_for'
/opt/system/vendor/bundle/ruby/2.4.0/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:994:in `request'
/opt/system/vendor/bundle/ruby/2.4.0/gems/faraday-0.12.2/lib/faraday/adapter/net_http_persistent.rb:26:in `perform_request'
/opt/system/vendor/bundle/ruby/2.4.0/gems/faraday-0.12.2/lib/faraday/adapter/net_http.rb:38:in `block in call'
/opt/system/vendor/bundle/ruby/2.4.0/gems/faraday-0.12.2/lib/faraday/adapter/net_http.rb:85:in `with_net_http_connection'
/opt/system/vendor/bundle/ruby/2.4.0/gems/faraday-0.12.2/lib/faraday/adapter/net_http.rb:33:in `call'
/opt/system/vendor/bundle/ruby/2.4.0/gems/faraday-0.12.2/lib/faraday/rack_builder.rb:141:in `build_response'
/opt/system/vendor/bundle/ruby/2.4.0/gems/faraday-0.12.2/lib/faraday/connection.rb:386:in `run_request'
/opt/system/vendor/bundle/ruby/2.4.0/gems/faraday-0.12.2/lib/faraday/connection.rb:149:in `get'
/opt/system/vendor/bundle/ruby/2.4.0/gems/pisoni-1.26.0/lib/3scale/core/api_client/operations.rb:103:in `api_http'
/opt/system/vendor/bundle/ruby/2.4.0/gems/pisoni-1.26.0/lib/3scale/core/api_client/operations.rb:186:in `api'
/opt/system/lib/tasks/boot.rake:6:in `block (2 levels) in <top (required)>'
/opt/system/vendor/bundle/ruby/2.4.0/gems/bugsnag-6.11.1/lib/bugsnag/integrations/rake.rb:18:in `execute_with_bugsnag'
/opt/system/vendor/bundle/ruby/2.4.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `load'
/opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `kernel_load'
/opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:28:in `run'
/opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.17.3/lib/bundler/cli.rb:463:in `exec'
/opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.17.3/lib/bundler/cli.rb:27:in `dispatch'
/opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.17.3/lib/bundler/cli.rb:18:in `start'
/opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.17.3/exe/bundle:30:in `block in <top (required)>'
/opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.17.3/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.17.3/exe/bundle:22:in `<top (required)>'
/opt/rh/rh-ruby24/root/usr/local/bin/bundle:23:in `load'
/opt/rh/rh-ruby24/root/usr/local/bin/bundle:23:in `<main>'

Caused by:
Net::OpenTimeout: execution expired
/opt/system/vendor/bundle/ruby/2.4.0/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:700:in `start'
/opt/system/vendor/bundle/ruby/2.4.0/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:631:in `connection_for'
/opt/system/vendor/bundle/ruby/2.4.0/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:994:in `request'
/opt/system/vendor/bundle/ruby/2.4.0/gems/faraday-0.12.2/lib/faraday/adapter/net_http_persistent.rb:26:in `perform_request'
/opt/system/vendor/bundle/ruby/2.4.0/gems/faraday-0.12.2/lib/faraday/adapter/net_http.rb:38:in `block in call'
/opt/system/vendor/bundle/ruby/2.4.0/gems/faraday-0.12.2/lib/faraday/adapter/net_http.rb:85:in `with_net_http_connection'
/opt/system/vendor/bundle/ruby/2.4.0/gems/faraday-0.12.2/lib/faraday/adapter/net_http.rb:33:in `call'
/opt/system/vendor/bundle/ruby/2.4.0/gems/faraday-0.12.2/lib/faraday/rack_builder.rb:141:in `build_response'
/opt/system/vendor/bundle/ruby/2.4.0/gems/faraday-0.12.2/lib/faraday/connection.rb:386:in `run_request'
/opt/system/vendor/bundle/ruby/2.4.0/gems/faraday-0.12.2/lib/faraday/connection.rb:149:in `get'
/opt/system/vendor/bundle/ruby/2.4.0/gems/pisoni-1.26.0/lib/3scale/core/api_client/operations.rb:103:in `api_http'
/opt/system/vendor/bundle/ruby/2.4.0/gems/pisoni-1.26.0/lib/3scale/core/api_client/operations.rb:186:in `api'
/opt/system/lib/tasks/boot.rake:6:in `block (2 levels) in <top (required)>'
/opt/system/vendor/bundle/ruby/2.4.0/gems/bugsnag-6.11.1/lib/bugsnag/integrations/rake.rb:18:in `execute_with_bugsnag'
/opt/system/vendor/bundle/ruby/2.4.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `load'
/opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `kernel_load'
/opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:28:in `run'
/opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.17.3/lib/bundler/cli.rb:463:in `exec'
/opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.17.3/lib/bundler/cli.rb:27:in `dispatch'
/opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.17.3/lib/bundler/cli.rb:18:in `start'
/opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.17.3/exe/bundle:30:in `block in <top (required)>'
/opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.17.3/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.17.3/exe/bundle:22:in `<top (required)>'
/opt/rh/rh-ruby24/root/usr/local/bin/bundle:23:in `load'
/opt/rh/rh-ruby24/root/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => boot => boot:all => boot:backend
(See full trace by running task with --trace)
[root@bastion 0 ~/installation master ↑·2|✔]# 
```

**Comment by jessesarn** [comment]
Looking at the output from 'oc events -n 3scale' on your cluster, you can see the backend-listener pod is failing to schedule due to insufficient resources:
```
$ ssh master.atlanta-f22d.example.opentlc.com 'sudo oc get events -n 3scale' | grep -v Normal
LAST SEEN   FIRST SEEN   COUNT     NAME                                           KIND                    SUBOBJECT                                TYPE      REASON              SOURCE                                 MESSAGE
1h          1h           1         system-mysql-1-v6rgh.15bd04b8601c67c3          Pod                     spec.containers{system-mysql}            Warning   Unhealthy           kubelet, node1.atlanta-f22d.internal   Readiness probe failed: sh: cannot set terminal process group (-1): Inappropriate ioctl for device
sh: no job control in this shell
ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1' (111)

1h        1h        2         system-mysql-1-v6rgh.15bd04b8d910e2fb       Pod                     spec.containers{system-mysql}     Warning   Unhealthy                     kubelet, node1.atlanta-f22d.internal   Liveness probe failed: dial tcp 10.1.4.228:3306: connect: connection refused
1h        1h        4         zync-que-1-4kgxm.15bd04b56d9186ee           Pod                     spec.containers{que}              Warning   BackOff                       kubelet, node1.atlanta-f22d.internal   Back-off restarting failed container
1h        1h        223       backend-listener-1-c9bhd.15bd04af2f8df1a2   Pod                                                       Warning   FailedScheduling              default-scheduler                      0/3 nodes are available: 1 Insufficient cpu, 2 node(s) didn't match node selector.
1m        1h        335       system-app-1-hook-pre.15bd04be3adc99b8      Pod                     spec.containers{lifecycle}        Warning   BackOff                       kubelet, node1.atlanta-f22d.internal   Back-off restarting failed container
```
When I looked at the nodes, there is only 1 compute node which I imagine is because the OCP workshop uses default value for users=5.  The integreatly workshops default to 15 in order to get 3 compute nodes.  If you provision a new OCP workshop and increase the users value to 15, you should get enough resources to handle all of the components for the full install.

**Comment by davidffrench** [comment]
Thanks for the analysis @jessesarn . I am running an uninstall on my cluster now and I can run the install to verify this branch then

**Comment by odra** [comment]
Just ran on mine and it worked.. ups ready check passed after 30 tries or so, a bit longer than usual which means the fix worked

**Comment by davidffrench** [comment]
Verified and it worked on mine

**Pull request merged**
