### PR TITLE
Update zync pod ready check

### PR DESCRIPTION
**Pull request by sedroche**
## Additional Information
Jira: https://issues.jboss.org/browse/INTLY-2479

Refining the pod status ready check.

### CODE REVIEW

**Comment by jasonmadigan** [comment]
@sedroche ping whoever you need to get this reviewed, would like to have landed so we can take another stab at a more successful upgrade today.

**Comment by odra** [comment]
I can give it a try

**Comment by odra** [comment]
Note: tested in pds

**Comment by maleck13** [comment]
If we are happy here lets get it merged so it is picked up in the next upgrade run

**Pull request merged**
