### PR TITLE
Intly 775 update che to codeready GA 1.0.0

### PR DESCRIPTION
**Pull request by maleck13**
## Additional Information
In order to do this we needed to create a non system:admin user. So we create a new user and give him clusteradmin perms to run the codeready install

## Verification Steps

#RHPDS 
Run the installer from a fresh cluster with the regular installation command
Go to the codeready ns
Use the url and login with the evals01 or admin@example.com user
Ensure you can create 2 workspaces

#OSD 
As above except you need to pass ```-e 'create_cluster_admin=false' -e 'eval_seed_users_count=1' ``` flag as we don't run as system:admin on OSD

### CODE REVIEW

**Comment by maleck13** [comment]
@StevenTobin this could be given a run on OSD to see if there is something fundamental we need to change

**Comment by odra** [comment]
Getting this error: https://gist.github.com/odra/a857484b9184943c6968b7e7f2c9645d

I am running it as the default rhpds admin user instead of system:admin.

**Comment by maleck13** [comment]
@odra ok with this change now. Ok to approve. I am doing the web app now

**Comment by david-martin** [comment]
@pmccarthy Can you test this on a multi-AZ, multi-node (at least 2 nodes in each AZ) cluster.

**Comment by maleck13** [comment]
@odra @david-martin perhaps we should approve and merge back as we know it is working RHPDS and then deal with any fall out on OSD PJS clusters as it appears in smaller changes

**Comment by david-martin** [comment]
> perhaps we should approve and merge back

I don't mind if it's on the test plan for the RC

**Pull request merged**
