### PR TITLE
Intly 6500 update 3scale

### PR DESCRIPTION
**Pull request by jessesarn**
## Additional Information
https://issues.redhat.com/browse/INTLY-6500

Upgrades 3scale from 2.7 to 2.8

## Verification Steps
As the verifier of the PR the following process should be done:

### Installation Verification
- Ensure the author of the PR has attached a log of the installation run from his branch to the jira or pr and check that it exited as expected.
- Verify the fresh installation is correct on cluster provided by PR author 
### Upgrade Verification
- After installation verification, notify the PR author to begin an upgrade on their cluster
- Ensure the developer of the PR has attached a log of the upgrade run from his branch to the jira or pr and check that it exited as expected. 
- If possible, look at the tasks that ran and see they match the PR
- Verify the upgrade is correct on cluster provided by PR author 

Log of upgrade: https://gist.github.com/04ec9e140d222c6dd4e7e1b483f3e070
Diff of all pod/container images before vs. after: https://gist.github.com/jessesarn/04ec9e140d222c6dd4e7e1b483f3e070#file-diff-of-i8-get-image-report-before-vs-after

## Checklist

- [ ] Updated [Changelog](https://github.com/integr8ly/installation/blob/master/CHANGELOG.md)
- [ ] Tested Installation
- [ ] Tested Uninstallation
- [ ] Tested or Created follow on for Upgrade

Is an upgrade task required and are there additional steps needed to test this?
- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by JameelB** [comment]
code changes looks good to me.

@jessesarn should the customisation not have picked up the 3scale version to be `2.8.0` instead of `2.7.0` [here](https://gist.github.com/jessesarn/04ec9e140d222c6dd4e7e1b483f3e070#file-integreatly-upgrade-log-L2112)?

**Comment by jessesarn** [comment]
@JameelB Good catch.  Yeah, I would expect it should report the new version.  I'll run it again on my new cluster to see if I can find out what is missing.

**Comment by jessesarn** [comment]
ah, we made a mistake.  The attached  integreatly-upgrade.log includes output from the upgrade from 1.6.0 -> 1.6.1 and then 1.6.1 -> master.

The 2.7.0.GA you saw in line 2112 which is still for the 1.6.1 upgrade.  You can tell its for the 1.6.1, because the paths for the 1.6.1 upgrade are all within /root/installation-1.6.1/...

The upgrade from 1.6.1 -> master begins on line [3822](https://gist.github.com/jessesarn/04ec9e140d222c6dd4e7e1b483f3e070#file-integreatly-upgrade-log-L3822).  You can't actually see the string used for the 3scale version in the later output because the logic for upgrades changed signficantly between v1.6 and master.  The logic in master does a straight delete and recreate of the manifest from the manifest.yml included in the installer inventories group_vars.

**Comment by JameelB** [comment]
/lgtm

@jessesarn may need to ping an approver as i'm not on that list

**Comment by jessesarn** [comment]
got it covered. I'm an approver ;)
/approve

**Pull request merged**
