### PR TITLE
INTLY-6419 Cherrypick 

### PR DESCRIPTION
**Pull request by trdoyle81**
@pawelpaszki  - cherrypicked to v1.7

Add the steps required to check this change. Following an example.

1. Go to `XX >> YY >> SS`
2. Create a new item `N` with the info `X`
3. Try to edit this item
4. Check if in the left menu the feature X is not so long present.
-->

## Checklist

- [ ] Updated [Changelog](https://github.com/integr8ly/installation/blob/master/CHANGELOG.md)
- [ ] Tested Installation
- [ ] Tested Uninstallation
- [ ] Tested or Created follow on for Upgrade

Is an upgrade task required and are there additional steps needed to test this?
- [ ] Yes
- [ x] No

### CODE REVIEW

**Comment by trdoyle81** [comment]
@JameelB

**Comment by JameelB** [comment]
@jessesarn mind giving us an approval here :)

**Pull request merged**
