### PR TITLE
install apicurito from template

### PR DESCRIPTION
**Pull request by philbrookes**
## Motivation
INTLY-307

### CODE REVIEW

**Comment by odra** [comment]
code looks ok, will give it  a try once my cluster is ready.

**Comment by tremes** [comment]
I am installing it from the Phil's branch. I'll let you know once I am done with testing.

**Comment by tremes** [comment]
@philbrookes Can you please rebase your branch? I am getting:
`TASK [msbroker : Get 3scale dashboard url] *************************************
fatal: [127.0.0.1]: FAILED! => {"changed": true, "cmd": "oc get route/system-provider-admin-route -o jsonpath='{.spec.host}' -n 3scale"
`

**Comment by odra** [comment]
I think this pr needs a rebase since those 3scale errors were fixed in another pr due to 3scale operator changes.

**Comment by aidenkeating** [comment]
Closing as changes included in #274

**Pull request closed without merging**
