### PR TITLE
AEROGEAR-9691 - Rename MobileClient CRD group

### PR DESCRIPTION
**Pull request by aliok**
JIRA: https://issues.jboss.org/browse/AEROGEAR-9691

Merging prereqs:
* https://github.com/aerogear/mobile-developer-console-operator/pull/40 is merged
* MDC operator image is created and tagged (as 0.1.8)

### CODE REVIEW

**Comment by wei-lee** [comment]
@aliok I guess we might only want to do this when mdc is also updated?

**Comment by aliok** [comment]
@wei-lee https://github.com/aerogear/mobile-developer-console-operator/pull/40 is a prerequisite for this PR and the MDC change is a prerequisite for https://github.com/aerogear/mobile-developer-console-operator/pull/40
So, MDC is also getting an update.

**Comment by wei-lee** [comment]
@aliok is this PR ready for merge then? If there are files being removed from the mdc operator, can you also check the resources in the mdc role (see https://github.com/integr8ly/installation/blob/master/roles/mdc/defaults/main.yml#L6) and see if some of them should be removed?

**Comment by aliok** [comment]
@wei-lee 

> @aliok is this PR ready for merge then? 

Waiting for the MDC operator image to arrive at Quay. Then we can merge.

> If there are files being removed from the mdc operator, can you also check the resources in the mdc role (see https://github.com/integr8ly/installation/blob/master/roles/mdc/defaults/main.yml#L6) and see if some of them should be removed?

Yes. Strange thing is, I wasn't able to find references to those deleted files. They were not used in the installer.

**Comment by aliok** [comment]
@odra @wei-lee mind merging this one? Images are ready on Quay

**Comment by aliok** [comment]
@grdryn @wei-lee can you take ownership on this PR?
Once this PR is merged, we can resolve the ticket https://issues.jboss.org/browse/AEROGEAR-9691

**Comment by grdryn** [comment]
@aliok :+1:

**Comment by grdryn** [comment]
Closing this as it's now superseded by #825

**Pull request closed without merging**
