### PR TITLE
INTLY-7166

### PR DESCRIPTION
**Pull request by laurafitzgerald**
## Additional Information
https://issues.redhat.com/browse/INTLY-7166

### Installation Verification
No Install changes here
### Upgrade Verification

Install release 1.6.1 - [Logs](https://gist.github.com/laurafitzgerald/2e215150fc3feec6680eabacce216e5c)
Install backup stuff - [Logs](https://gist.github.com/laurafitzgerald/ecc2ad50dbe7e16fe6b16466a1536b8d)
Cronjob Version
Screenshot 2020-05-01 at 12 01 48
Screenshot 2020-05-01 at 12 02 04
Fuse Workaround steps ran 
```
oc import-image syndesis-operator:1.6 --from=registry.redhat.io/fuse7/fuse-online-operator:1.6 --confirm -n fuse
oc import-image syndesis-s2i:1.6 --from=registry.redhat.io/fuse7/fuse-ignite-s2i:1.6 --confirm -n fuse
```
Upgrade from this branch - [Logs](https://gist.github.com/laurafitzgerald/4c352db025c5726b7d6e506a867d1b19)
Keycloak on 1.6.1
Screenshot 2020-05-01 at 14 37 39

Keycloak cr patched
Screenshot 2020-05-01 at 14 20 45

Cronjob version
Screenshot 2020-05-01 at 14 25 16

## Checklist
- [ ] Updated [Changelog](https://github.com/integr8ly/installation/blob/master/CHANGELOG.md)
- [ ] Tested Installation
- [ ] Tested Uninstallation
- [x] Tested or Created follow on for Upgrade

Is an upgrade task required and are there additional steps needed to test this?
- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by pawelpaszki** [comment]
looks good to me. @jessesarn can you please have a look as well and approve

**Comment by JameelB** [comment]
@pawelpaszki Shall i test this first on osd?

**Comment by pawelpaszki** [comment]
@JameelB - makes sense

**Comment by JameelB** [comment]
/hold 

hold on merging this until it's verified on osd https://github.com/integr8ly/installation/pull/1344

**Comment by laurafitzgerald** [comment]
Upgrade job here: https://qe-tower.rhmw.io/#/jobs/playbook/2923

Verification on rhmds-qe1
Cronjob images
Screenshot 2020-05-01 at 19 06 50

**Comment by laurafitzgerald** [comment]
ping @pawelpaszki @jessesarn see above.

**Pull request merged**
