### PR TITLE
fix(Error: jsonpointer module is not available): Add var ansible_python_interpreter

### PR DESCRIPTION
**Pull request by camilamacedo86**
## Motivation
Fix the issue: https://github.com/integr8ly/installation/issues/156

## What
Unable to install 

## Why
Ansible is using a version of python which hasn't this module.

## How
Adding valid info in README to solve it.

## Checklist:

- [X] Code has been tested locally by PR requester
- [ ] Changes have been successfully verified by another team member 

## Progress

- [X] Finished task

### CODE REVIEW

**Comment by philbrookes** [comment]
This looks fine to me, but I do not have a mac to test this on.

**Comment by camilamacedo86** [comment]
@philbrookes shows that it occurs in any SO. However, is required it has more than on python installed. Please, could you check this one and approve if possible?

**Comment by austincunningham** [comment]
reproduced this issue installing on minishift on liniux mint
```
/ TASK rhsso : user generation: evals01@example.com] add user \
\ to realm template /tmp/keycloak-realm.json                  /
 -------------------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

task path: /home/austincunningham/repo-integr8ly/installation/evals/roles/rhsso/tasks/_inject_user.yml:17
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1542881352.22-189954200839593 `" && echo ansible-tmp-1542881352.22-189954200839593="` echo /root/.ansible/tmp/ansible-tmp-1542881352.22-189954200839593 `" ) && sleep 0'
Using module file /home/austincunningham/repo-integr8ly/installation/evals/library/json_modify.py
<127.0.0.1> PUT /home/austincunningham/.ansible/tmp/ansible-local-18793YSt6sY/tmpUt7z92 TO /root/.ansible/tmp/ansible-tmp-1542881352.22-189954200839593/json_modify.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1542881352.22-189954200839593/ /root/.ansible/tmp/ansible-tmp-1542881352.22-189954200839593/json_modify.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1542881352.22-189954200839593/json_modify.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1542881352.22-189954200839593/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_0eH56k/ansible_module_json_modify.py", line 7, in <module>
    import jsonpointer

fatal: [127.0.0.1]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "action": "extend", 
            "append": null, 
            "data": {
                "apiVersion": "aerogear.org/v1alpha1", 
                "kind": "KeycloakRealm", 
                "metadata": {
                    "name": "openshift"
                }, 
                "spec": {
                    "clients": [
                        {
                            "clientAuthenticatorType": "client-secret", 
                            "clientId": "openshift-client", 
                            "enabled": true, 
                            "id": "openshift-client", 
                            "outputSecret": "openshift-client-client", 
                            "redirectUris": [
                                "https://tutorial-web-app-webapp.192.168.42.70.nip.io", 
                                "https://192.168.42.70:8443/*", 
                                "http://localhost:3006*"
                            ], 
                            "secret": "c00b10fee3d9b5a1262370930b9d2907efc4a5cf47b0b6e4257f5bd770d8f26b4572ed019b9c4f71bb025e92068a95eab5695e1021772cc5a81ac50376cb61f5", 
                            "standardFlowEnabled": true
                        }, 
                        {
                            "access": {
                                "configure": true, 
                                "manage": true, 
                                "view": true
                            }, 
                            "clientAuthenticatorType": "client-secret", 
                            "clientId": "3scale", 
                            "enabled": true, 
                            "fullScopeAllowed": true, 
                            "id": "3scale", 
                            "outputSecret": "3scale-client", 
                            "protocolMappers": [
                                {
                                    "config": {
                                        "access.token.claim": "true", 
                                        "claim.name": "given_name", 
                                        "id.token.claim": "true", 
                                        "jsonType.label": "String", 
                                        "user.attribute": "firstName", 
                                        "userinfo.token.claim": "true"
                                    }, 
                                    "consentRequired": true, 
                                    "consentText": "${givenName}", 
                                    "name": "given name", 
                                    "protocol": "openid-connect", 
                                    "protocolMapper": "oidc-usermodel-property-mapper"
                                }, 
                                {
                                    "config": {
                                        "access.token.claim": "true", 
                                        "claim.name": "email_verified", 
                                        "id.token.claim": "true", 
                                        "jsonType.label": "boolean", 
                                        "user.attribute": "emailVerified", 
                                        "userinfo.token.claim": "true"
                                    }, 
                                    "consentRequired": false, 
                                    "consentText": "${emailVerified}", 
                                    "name": "email verified", 
                                    "protocol": "openid-connect", 
                                    "protocolMapper": "oidc-usermodel-property-mapper"
                                }, 
                                {
                                    "config": {
                                        "access.token.claim": "true", 
                                        "claim.name": "preferred_username", 
                                        "id.token.claim": "true", 
                                        "jsonType.label": "String", 
                                        "user.attribute": "username", 
                                        "userinfo.token.claim": "true"
                                    }, 
                                    "consentRequired": true, 
                                    "consentText": "${username}", 
                                    "name": "username", 
                                    "protocol": "openid-connect", 
                                    "protocolMapper": "oidc-usermodel-property-mapper"
                                }, 
                                {
                                    "config": {
                                        "access.token.claim": "true", 
                                        "id.token.claim": "true"
                                    }, 
                                    "consentRequired": true, 
                                    "consentText": "${fullName}", 
                                    "name": "full name", 
                                    "protocol": "openid-connect", 
                                    "protocolMapper": "oidc-full-name-mapper"
                                }, 
                                {
                                    "config": {
                                        "access.token.claim": "true", 
                                        "claim.name": "family_name", 
                                        "id.token.claim": "true", 
                                        "jsonType.label": "String", 
                                        "user.attribute": "lastName", 
                                        "userinfo.token.claim": "true"
                                    }, 
                                    "consentRequired": true, 
                                    "consentText": "${familyName}", 
                                    "name": "family name", 
                                    "protocol": "openid-connect", 
                                    "protocolMapper": "oidc-usermodel-property-mapper"
                                }, 
                                {
                                    "config": {
                                        "attribute.name": "Role", 
                                        "attribute.nameformat": "Basic", 
                                        "single": "false"
                                    }, 
                                    "consentRequired": false, 
                                    "name": "role list", 
                                    "protocol": "saml", 
                                    "protocolMapper": "saml-role-list-mapper"
                                }, 
                                {
                                    "config": {
                                        "access.token.claim": "true", 
                                        "claim.name": "email", 
                                        "id.token.claim": "true", 
                                        "jsonType.label": "String", 
                                        "user.attribute": "email", 
                                        "userinfo.token.claim": "true"
                                    }, 
                                    "consentRequired": true, 
                                    "consentText": "${email}", 
                                    "name": "email", 
                                    "protocol": "openid-connect", 
                                    "protocolMapper": "oidc-usermodel-property-mapper"
                                }, 
                                {
                                    "config": {
                                        "access.token.claim": "true", 
                                        "claim.name": "org_name", 
                                        "id.token.claim": "true", 
                                        "jsonType.label": "String", 
                                        "user.attribute": "org_name", 
                                        "userinfo.token.claim": "true"
                                    }, 
                                    "consentRequired": false, 
                                    "name": "org_name", 
                                    "protocol": "openid-connect", 
                                    "protocolMapper": "oidc-usermodel-attribute-mapper"
                                }
                            ], 
                            "redirectUris": [
                                "https://3scale-admin.192.168.42.70.nip.io/*"
                            ], 
                            "rootUrl": "https://3scale-admin.192.168.42.70.nip.io", 
                            "secret": "f6ca5b5e06ea29f3b29b64e9b3d8aacbe396f0a47a29636a48f056f9fb503baea3549565055238ead10c79815406e878617b3276c4d21f7181dc18668736e9c6", 
                            "standardFlowEnabled": true
                        }, 
                        {
                            "access": {
                                "configure": true, 
                                "manage": true, 
                                "view": true
                            }, 
                            "adminUrl": "https://launcher-sso-launcher.192.168.42.70.nip.io", 
                            "bearerOnly": false, 
                            "clientAuthenticatorType": "client-secret", 
                            "clientId": "launcher-openshift-users", 
                            "consentRequired": false, 
                            "defaultRoles": [
                                "read-token"
                            ], 
                            "directAccessGrantsEnabled": false, 
                            "enabled": true, 
                            "frontchannelLogout": false, 
                            "fullScopeAllowed": true, 
                            "id": "launcher-openshift-users", 
                            "implicitFlowEnabled": false, 
                            "name": "Launcher Cloud Service Cluster Users", 
                            "nodeReRegistrationTimeout": 0, 
                            "notBefore": 0, 
                            "outputSecret": "launcher-openshift-users-client", 
                            "protocol": "openid-connect", 
                            "protocolMappers": [
                                {
                                    "config": {
                                        "access.token.claim": "true", 
                                        "claim.name": "family_name", 
                                        "id.token.claim": "true", 
                                        "jsonType.label": "String", 
                                        "user.attribute": "lastName", 
                                        "userinfo.token.claim": "true"
                                    }, 
                                    "consentRequired": true, 
                                    "consentText": "${familyName}", 
                                    "name": "family name", 
                                    "protocol": "openid-connect", 
                                    "protocolMapper": "oidc-usermodel-property-mapper"
                                }, 
                                {
                                    "config": {
                                        "access.token.claim": "true", 
                                        "claim.name": "given_name", 
                                        "id.token.claim": "true", 
                                        "jsonType.label": "String", 
                                        "user.attribute": "firstName", 
                                        "userinfo.token.claim": "true"
                                    }, 
                                    "consentRequired": true, 
                                    "consentText": "${givenName}", 
                                    "name": "given name", 
                                    "protocol": "openid-connect", 
                                    "protocolMapper": "oidc-usermodel-property-mapper"
                                }, 
                                {
                                    "config": {
                                        "access.token.claim": "true", 
                                        "claim.name": "preferred_username", 
                                        "id.token.claim": "true", 
                                        "jsonType.label": "String", 
                                        "user.attribute": "username", 
                                        "userinfo.token.claim": "true"
                                    }, 
                                    "consentRequired": true, 
                                    "consentText": "${username}", 
                                    "name": "username", 
                                    "protocol": "openid-connect", 
                                    "protocolMapper": "oidc-usermodel-property-mapper"
                                }, 
                                {
                                    "config": {
                                        "access.token.claim": "true", 
                                        "claim.name": "email", 
                                        "id.token.claim": "true", 
                                        "jsonType.label": "String", 
                                        "user.attribute": "email", 
                                        "userinfo.token.claim": "true"
                                    }, 
                                    "consentRequired": true, 
                                    "consentText": "${email}", 
                                    "name": "email", 
                                    "protocol": "openid-connect", 
                                    "protocolMapper": "oidc-usermodel-property-mapper"
                                }, 
                                {
                                    "config": {
                                        "access.token.claim": "true", 
                                        "id.token.claim": "true"
                                    }, 
                                    "consentRequired": true, 
                                    "consentText": "${fullName}", 
                                    "name": "full name", 
                                    "protocol": "openid-connect", 
                                    "protocolMapper": "oidc-full-name-mapper"
                                }, 
                                {
                                    "config": {
                                        "attribute.name": "Role", 
                                        "attribute.nameformat": "Basic", 
                                        "single": "false"
                                    }, 
                                    "consentRequired": false, 
                                    "name": "role list", 
                                    "protocol": "saml", 
                                    "protocolMapper": "saml-role-list-mapper"
                                }
                            ], 
                            "publicClient": false, 
                            "redirectUris": [
                                "https://launcher-sso-launcher.192.168.42.70.nip.io", 
                                "https://launcher-sso-launcher.192.168.42.70.nip.io/*"
                            ], 
                            "rootUrl": "https://launcher-sso-launcher.192.168.42.70.nip.io", 
                            "secret": "00e65657611689a01d959467ba99ae62b111769110be38c259bdf2cf6a56e78a8d061d360616f19a14c4959c5b586c97e8794f97b58450c5a42d2af3ee416b1e", 
                            "serviceAccountsEnabled": false, 
                            "standardFlowEnabled": true, 
                            "surrogateAuthRequired": false, 
                            "useTemplateConfig": false, 
                            "useTemplateMappers": false, 
                            "useTemplateScope": false, 
                            "webOrigins": [
                                "https://launcher-sso-launcher.192.168.42.70.nip.io", 
                                "https://launcher-sso-launcher.192.168.42.70.nip.io/*"
                            ]
                        }
                    ], 
                    "displayName": "openshift", 
                    "enabled": true, 
                    "id": "openshift", 
                    "realm": "openshift", 
                    "users": [
                        {
                            "attributes": {}, 
                            "clientRoles": {
                                "account": [
                                    "manage-account", 
                                    "view-profile"
                                ]
                            }, 
                            "email": "evals-admin@example.com", 
                            "emailVerified": true, 
                            "enabled": true, 
                            "outputSecret": "evals-admin-user-credentials", 
                            "password": "Password1", 
                            "realmRoles": [
                                "offline_access", 
                                "uma_authorization"
                            ], 
                            "username": "evals-admin@example.com"
                        }, 
                        {
                            "attributes": {}, 
                            "clientRoles": {
                                "account": [
                                    "manage-account", 
                                    "view-profile"
                                ]
                            }, 
                            "email": "admin@example.com", 
                            "emailVerified": true, 
                            "enabled": true, 
                            "outputSecret": "admin-user-credentials", 
                            "password": "Password1", 
                            "realmRoles": [
                                "offline_access", 
                                "uma_authorization"
                            ], 
                            "username": "admin@example.com"
                        }, 
                        {
                            "attributes": {}, 
                            "clientRoles": {
                                "account": [
                                    "manage-account", 
                                    "view-profile"
                                ]
                            }, 
                            "email": "evals@example.com", 
                            "emailVerified": true, 
                            "enabled": true, 
                            "outputSecret": "test-user-credentials", 
                            "password": "Password1", 
                            "realmRoles": [
                                "offline_access", 
                                "uma_authorization"
                            ], 
                            "username": "evals@example.com"
                        }
                    ]
                }
            }, 
            "extend": [
                {
                    "attributes": {}, 
                    "clientRoles": {
                        "account": [
                            "manage-account", 
                            "view-profile"
                        ]
                    }, 
                    "email": "evals01@example.com", 
                    "emailVerified": true, 
                    "enabled": true, 
                    "outputSecret": "evals01-example.com-credentials", 
                    "password": "Password1", 
                    "realmRoles": [
                        "offline_access", 
                        "uma_authorization"
                    ], 
                    "username": "evals01@example.com"
                }
            ], 
            "pointer": "/spec/users", 
            "update": null
        }
    }, 
    "msg": "jsonpointer module is not available"
}

```

**Comment by camilamacedo86** [comment]
@austincunningham really thank you for confirming to us that it is related has more than on python installed locally and not to an specific SO at all.

**Comment by austincunningham** [comment]
@camilamacedo86 workaround was to 
```
pip install jsonpointer
```

**Comment by camilamacedo86** [comment]
@austincunningham did you have more than one version installed? If the version of the python did not have the module I think the pip install jsonpointer will solve too. However, the var will ensure to use a the ansible version.

**Comment by austincunningham** [comment]
@camilamacedo86 
```
➜ python --version
Python 2.7.12
➜  python3 --version
Python 3.5.2
```

**Pull request merged**
