### PR TITLE
INTLY-2544 - allow customer-admins view 3Scale logs in Kibana

### PR DESCRIPTION
**Pull request by matskiv**
## Additional Information
JIRA: https://issues.redhat.com/browse/INTLY-2544

## Verification Steps
As the verifier of the PR the following process should be done:

### Installation Verification
- Ensure the author of the PR has attached a log of the installation run from his branch to the jira or pr and check that it exited as expected.
- Verify the fresh installation is correct on cluster provided by PR author 

Skipped. IMHO for this particular change, testing the upgrade is sufficient to execute new code. 

### Upgrade Verification
- After installation verification, notify the PR author to begin an upgrade on their cluster
- Ensure the developer of the PR has attached a log of the upgrade run from his branch to the jira or pr and check that it exited as expected. 
- If possible, look at the tasks that ran and see they match the PR
- Verify the upgrade is correct on cluster provided by PR author 

Run the upgrade playbook
Login into OpenShift as customer-admin user
Open Kibana console (https://kibana.apps...) and verify that 3Scale logs are displayed 

Logs: https://gist.github.com/matskiv/881408502c54cb731610dbd20d1f7569
Screenshot from Kibana (logged in as customer-admin):
Screenshot 2020-03-23 at 16 27 43

- [x] Updated [Changelog](https://github.com/integr8ly/installation/blob/master/CHANGELOG.md)
- [ ] Tested Installation
- [ ] Tested Uninstallation
- [x] Tested or Created follow on for Upgrade

Is an upgrade task required and are there additional steps needed to test this?
- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by matskiv** [comment]
@jessesarn @austincunningham Can you please review this, when you have time...

**Comment by matskiv** [comment]
Forgot to mention in the description.
This has been implemented with the support for `rhsso_seed_user_list` var. It was added to installer here - https://github.com/integr8ly/installation/pull/1242#issue-363706846

**Comment by austincunningham** [comment]
:eyes:

**Comment by austincunningham** [comment]
Verified 
/approve

**Pull request merged**
