### PR TITLE
set default cluster_type to pds

### PR DESCRIPTION
**Pull request by jessesarn**
https://issues.redhat.com/browse/INTLY-4368 - test install to rhpds cluster running now.

### CODE REVIEW

**Comment by jessesarn** [comment]
Provisioned an OCP workshop cluster and installed using the exact same command line that I had retrieved while diagnosing the Integreatly 1.6.0-rhpds provision documented in the JIRA.

Log from install:
https://gist.github.com/jessesarn/b98a252708e6b516a44d7e8a020e1452

**Comment by pawelpaszki** [comment]
install logs: https://gist.github.com/pawelpaszki/1200a482d0217771a040e73b76a2a459

**Comment by pmccarthy** [comment]
@jessesarn This one can be closed out as we don't want to update master with this workaround

**Pull request closed without merging**
