### PR TITLE
Explicitly remove the mdc oauthclient

### PR DESCRIPTION
**Pull request by david-martin**
## Additional Information
During uninstall, all oauthclients are removed https://gist.github.com/david-martin/ca1fdd8311a67d99818eacd022e2297c

This is incorrect. Only the mdc oauthclient should be removed.

## Verification Steps
As the verifier of the PR the following process should be done:

### Installation Verification
- Ensure the author of the PR has attached a log of the installation run from his branch to the jira or pr and check that it exited as expected.
- Verify the fresh installation is correct on cluster provided by PR author 
### Upgrade Verification
- After installation verification, notify the PR author to begin an upgrade on their cluster
- Ensure the developer of the PR has attached a log of the upgrade run from his branch to the jira or pr and check that it exited as expected. 
- If possible, look at the tasks that ran and see they match the PR
- Verify the upgrade is correct on cluster provided by PR author 

## Is an upgrade task required and are there additional steps needed to test this?

- [ ] Yes
- [x] No

- [x] Tested Installation
- [x] Tested Uninstallation
- [ ] Tested or Created follow on for Upgrade

### CODE REVIEW

**Comment by david-martin** [comment]
full log https://gist.github.com/david-martin/bf07be1914c0aa841a692cbe707e44e7

**Comment by david-martin** [comment]
@grdryn The process in the PR template was updated recently to put more upfront verification & proof on the PR creator that the PR does what it says it should do, hence the attached logs.
If you're happy with the code, and the log output, then job done.

It does need a second approver thought. ping @wei-lee @laurafitzgerald

**Comment by laurafitzgerald** [comment]
@david-martin This looks good to me. One comment would be that if this variable https://github.com/integr8ly/installation/blob/master/roles/mdc/defaults/main.yml#L5 is changed between versions then the oauthclient wont be found for an uninstall. Should we leave some comment with the variable that it shouldn't be changed?

**Comment by david-martin** [comment]
> Should we leave some comment with the variable that it shouldn't be changed?

I don't think that's necessary. 
Uninstall is only done during development & testing.
Typically the same version is used to uninstall as to install, or at most 1 version later if testing upgrades. 
Uninstall will not be run in a production cluster.

**Pull request merged**
