### PR TITLE
Intly 1425

### PR DESCRIPTION
**Pull request by maleck13**
## Additional Information

allow fuse to be installed in a openshift- namespace
## Verification Steps

provision from the branch
check the shared fuse namespace starts with ```openshift-```
login to the webapp ensure you can click through and login to the shared fuse instance

### CODE REVIEW

**Comment by JameelB** [comment]
:eyes: Will verify on PDS

**Comment by maleck13** [comment]
@JameelB thanks, but this is WIP at the moment will add the tag. Just wanted to share it with @aidenkeating etc

**Comment by maleck13** [comment]
ready for testing

**Comment by matskiv** [comment]
👀

**Pull request merged**
