### PR TITLE
Cherry pick changes from master

### PR DESCRIPTION
**Pull request by aidenkeating**
cherry-pick of:
* from https://github.com/integr8ly/installation/pull/354 (managed fuse install)
   39432eb0dc70f0aba5badeea7277d1628ee03f95
   19903fe857c7cfe2867fa5409c9cdc5d3d512845
* from https://github.com/integr8ly/installation/pull/358 (monitoring label on codeready namespace)
   a5ab7893b41bbbf7a1d8ee06d88cd3a32b91c548
* from https://github.com/integr8ly/installation/pull/359 (MSB fuse monitoring label change)
   01afa5ac3602e936730386f8cd394edbc9568852
* from https://github.com/integr8ly/installation/pull/352 (Webapp metadata version bump)
   fedb835348135610474b3f4da56588ee786a1210

### CODE REVIEW

**Comment by aidenkeating** [comment]
@maleck13 @mikenairn Mind taking a look?

@mikenairn There have been changes made to the MSB repo master too, I don't see a v1.2 branch there so I assume the release pipeline tags the current master of the MSB and uses that?

**Comment by pb82** [comment]
@maleck13 I verified that non-admin users can log in (and still have to go through the oauth flow) but i didn't test trying to access it in incognito mode, will do that now.

**Comment by pb82** [comment]
@aidenkeating @maleck13 Ok, i tried accessing both routes in incognito mode:

The TODO App route (todo) can be accesses by anyone withouth any authentication.
The Fuse route (syndesis) requires you to log in. Using an evals user gives you access.

Is that the expected bahaviour?

**Comment by aidenkeating** [comment]
@pb82 The TODO app route isn't fronted by the oauth-proxy, so I would expect that. I guess another question is, do we want to remove that TODO app in the installer?

**Comment by maleck13** [comment]
@pb82 @aidenkeating this sounds ok. If the operator installs the todo app lets leave it there for now.

**Comment by aidenkeating** [comment]
Just to confirm

[/] The `fuse` namespace is created
[/] I can login to managed fuse as any authenticated user
[/] The `fuse` namespace has a monitoring label:
```
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    alm-manager: operator-lifecycle-manager.olm-operator
    openshift.io/description: ""
    openshift.io/display-name: ""
    openshift.io/requester: integreatly-admin
    openshift.io/sa.scc.mcs: s0:c20,c15
    openshift.io/sa.scc.supplemental-groups: 1000410000/10000
    openshift.io/sa.scc.uid-range: 1000410000/10000
  creationTimestamp: 2019-02-15T10:09:39Z
  labels:
    integreatly-middleware-service: "true"
    monitoring-key: middleware
  name: fuse
  resourceVersion: "688551"
  selfLink: /api/v1/namespaces/fuse
  uid: ce1d08bf-3109-11e9-a8fe-02f1cd39efe6
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
```
[/] The `codeready` namespace has the monitoring label:
```
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    alm-manager: operator-lifecycle-manager.olm-operator
    openshift.io/description: ""
    openshift.io/display-name: ""
    openshift.io/requester: integreatly-admin
    openshift.io/sa.scc.mcs: s0:c22,c9
    openshift.io/sa.scc.supplemental-groups: 1000480000/10000
    openshift.io/sa.scc.uid-range: 1000480000/10000
  creationTimestamp: 2019-02-14T17:04:56Z
  labels:
    integreatly-middleware-service: "true"
    monitoring-key: middleware
  name: codeready
  resourceVersion: "12998"
  selfLink: /api/v1/namespaces/codeready
  uid: a77f3889-307a-11e9-a462-02f1cd39efe6
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
```
[/] A `fuse-*` namespace provisioned by the MSB has the `brokered-fuse-online` monitoring label:
```
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    alm-manager: operator-lifecycle-manager.olm-operator
    openshift.io/sa.scc.mcs: s0:c15,c0
    openshift.io/sa.scc.supplemental-groups: 1000210000/10000
    openshift.io/sa.scc.uid-range: 1000210000/10000
  creationTimestamp: 2019-02-15T10:19:54Z
  labels:
    monitoring-key: brokered-fuse-online
  name: fuse-3c0eae8b-310b-11e9-a437-0a580a010007
  resourceVersion: "694501"
  selfLink: /api/v1/namespaces/fuse-3c0eae8b-310b-11e9-a437-0a580a010007
  uid: 3d0a40cf-310b-11e9-af4d-02f1cd39efe6
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
```

**Comment by mikenairn** [comment]
> @maleck13 @mikenairn Mind taking a look?
> 
> @mikenairn There have been changes made to the MSB repo master too, I don't see a v1.2 branch there so I assume the release pipeline tags the current master of the MSB and uses that?

There is no v1.2 branch created on the MSB repo, or any other repo for that matter. The master branch will just be tagged during a release. This is set to change soon when we finish externalising everything.

**Comment by aidenkeating** [comment]
Just waiting on https://github.com/integr8ly/installation/pull/361 to make the namespace check more deterministic

**Comment by aidenkeating** [comment]
@pb82 I've cherry-picked the namespace check from https://github.com/integr8ly/installation/pull/361 . The verification of the various other commits are above. Happy for this to be merged?

**Pull request merged**
