### PR TITLE
INTLY-971 move to new RH-SSO 7.3.2

### PR DESCRIPTION
**Pull request by maleck13**
## Additional Information
We needed to change the default scopes for launcher GH IDP

## Verification Steps

install on RHPDS using the following command 

Note there is an issue with GH and Code Ready. However Code Ready is being updated so it is currently just a known issue until we can prove the issue still exists. 
```
ansible-playbook -i inventories/hosts.template playbooks/install.yml -e 'ns_prefix=openshift-' -e 'eval_self_signed_certs=true' -e 'eval_seed_users_count=1' -e 'rhsso_operator_release_tag=1.4.0-rc1'
```
Ensure 7.3.2.GA is installed as the backing SSO
You should then link up GH and launcher following the doc. 
Check you can login to each service as an evals user from the webapp
Ensure you can link to your GH account from Launcher
Code Ready will not be able to import GH stuff currently (we are waiting for the update to Code Ready before taking any further action)

## Is an upgrade task required and are there additional steps needed to test this?

There is a separate upgrade task

- [x] Tested Installation
- [x] Tested Uninstallation
- [x] Tested or Created follow on for Upgrade

### CODE REVIEW

**Comment by maleck13** [comment]
@aidenkeating confused by the comment?

**Comment by aidenkeating** [comment]
@maleck13 Apologies, it was a bit of a brain-dump. I'll approve, the Launcher SSO verification was successful.

The query was, whether this PR is also meant to include a version bump for the keycloak-operator, now that [the keycloak-operator PR for 7.3.2.GA](https://github.com/integr8ly/keycloak-operator/pull/69) is verified and can be merged? Or is this PR only meant to contain the Launcher SSO version update?

**Comment by maleck13** [comment]
@aidenkeating ahh ok yes. I understand I will create a new release of the kc operator and update this pr.

**Comment by maleck13** [comment]
@aidenkeating I have installed with the new Code Ready if you want to verify that you can do the GH integreation https://codeready-openshift-codeready.apps.wat-3cfb.openshiftworkshop.com

**Pull request merged**
