### PR TITLE
ON-HOLD - INTLY-2120 Include user sso instance in upgrade

### PR DESCRIPTION
**Pull request by david-martin**
## Additional Information
https://issues.jboss.org/browse/INTLY-2120

## Verification Steps

* Install from release-1.3.0 tag using the managed/install.yml playbook and set `-e backup_restore_install=true`
* From this PR branch, run the upgrade playbook with `-e backup_restore_install=true`
* Verify a new sso instance has been installed to the user-sso namespace
* Verify the customer-admin user can login & administer it
* Verify there is a monitoring check in Prometheus for the new sso instance
* Verify there is a cronjob for the new sso instance
  * `oc get cronjob -n user-sso`

## Is an upgrade task required and are there additional steps needed to test this?
this is the upgrade task

- [ ] Tested Installation
- [ ] Tested Uninstallation
- [ ] Tested or Created follow on for Upgrade

### CODE REVIEW

**Comment by JameelB** [comment]
:eyes:

**Comment by david-martin** [comment]
On hold, pending a reset of the ugprade playbook on master

**Comment by jasonmadigan** [comment]
@david-martin do we need to get this back to master?

**Comment by david-martin** [comment]
@maleck13 Are changes to add the user sso instance by default now on master?
Can this pr be closed?

**Comment by maleck13** [comment]
Yep out of date

**Pull request closed without merging**
