### PR TITLE
wait for apicurito pods to be ready

### PR DESCRIPTION
**Pull request by laurafitzgerald**
## Additional Information
https://issues.redhat.com/browse/INTLY-7192
**Changes**
Verify that the apicurito pods are running before moving on with the installation.

## Verification Steps
Installed to PDS here: https://master.lfitzger-df31.open.redhat.com/console/project/apicurito/overview
Logs:
_Install Success_
tbc
_Install Fail on not enough pods (updated the check to 3)_
https://gist.github.com/laurafitzgerald/59e9295285afb0768ec201aa82cd1475

### Installation Verification
Will post the logs

### Upgrade Verification
Just a wait so no upgrade needed?

## Checklist

- [ ] Updated [Changelog](https://github.com/integr8ly/installation/blob/master/CHANGELOG.md)
- [ ] Tested Installation
- [ ] Tested Uninstallation
- [ ] Tested or Created follow on for Upgrade

Is an upgrade task required and are there additional steps needed to test this?
- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by JameelB** [comment]
Verified that installation fails if apicurito was not deployed successfully. Logs: https://gist.github.com/JameelB/7b5cf253b107c707c617d80ecd6510fb

**Comment by laurafitzgerald** [comment]
/hold
Waiting for a new version of the templates.

**Comment by laurafitzgerald** [comment]
@JameelB what would think about merging this one as we've shown that the change here works. 
I can follow up with another pr to update the version of the templates.

**Comment by JameelB** [comment]
@laurafitzgerald that's fine. Approving based on the logs above.

/lgtm
/approve

**Comment by JameelB** [comment]
/approve

Approving based on logs and comments above.

**Pull request merged**
