### PR TITLE
amq-online update 1.1.0.GA

### PR DESCRIPTION
**Pull request by fh-automatron**
Created automatically by jenkins

### CODE REVIEW

**Comment by maleck13** [comment]
I was able to install with no issue however AMQ failed to provision from the webapp. Looking into it

**Comment by mikenairn** [comment]
@maleck13 Do you have more details of the error? We did have to update the webapp in order for this to work. @odra Were the webapp changes merged back to master for this?

**Comment by maleck13** [comment]
The service failed. Error provisioning ServiceInstance of ClusterServiceClass (K8S: "c3581d6c-edfd-3989-8d4f-1ac54f26d773" ExternalName: "amq-online-standard") at ClusterServiceBroker "enmasse": Status: 400; ErrorMessage: <nil>; Description: <nil>; ResponseError: <nil>

**Comment by odra** [comment]
Thta's the webapp error, should this valiue change as well: https://github.com/integr8ly/installation/tree/master/inventories/group_vars/all#L78 to 2.9.1?

**Comment by maleck13** [comment]
using https://github.com/integr8ly/installation/pull/567

**Comment by maleck13** [comment]
**Verified**
Install completes successfully
Login to webapp completes
Starting walkthrough provisions AMQ online as expected
Failed when logging into AMQ console (we need to specify the correct ns)

**Comment by maleck13** [comment]
Running uninstall and reinstall

**Comment by maleck13** [comment]
Was able to verify everything
Was able to complete WT with amq and fuse

**Pull request merged**
