### PR TITLE
bump version of the WTs

### PR DESCRIPTION
**Pull request by wei-lee**
## Additional Information
https://issues.redhat.com/browse/INTLY-4562
https://issues.redhat.com/browse/INTLY-4565

## Verification

The change is deployed to this cluster: https://tutorial-web-app-webapp.apps.rhmitest-a7a6.open.redhat.com/home.

You can try out WT3 and verify the correct user name is displayed.

- [ ] Tested Installation
- [ ] Tested Uninstallation
- [x] Tested or Created follow on for Upgrade

### CODE REVIEW

**Comment by davidffrench** [comment]
@wei-lee Do you have the cluster url, I will grab the webapp password and verify this

**Comment by wei-lee** [comment]
@davidffrench I have sent the cluster details to you via IM

**Comment by davidffrench** [comment]
Can confirm the issues are resolved on the linked cluster

**Comment by davidffrench** [comment]
Can be cherry-picked to master now aswell

/lgtm
/approve

**Pull request merged**
