### PR TITLE
INTLY-2752 Update msbroker to 0.0.7

### PR DESCRIPTION
**Pull request by david-martin**
## Additional Information
https://issues.jboss.org/browse/INTLY-2752

## Verification Steps

Install

1. Verify install completes
2. Verify the new clusterrole & clusterrolebinding exists `oc get clusterrole managed-service-role-for-syndesis-operator` `oc get clusterrolebinding default-cluster-account-managed-service-for-syndesis-operator`

Upgrade

1. Verify upgrade from 1.4.1 succeeds
2. Verify the new clusterrole & clusterrolebinding exists `oc get clusterrole managed-service-role-for-syndesis-operator` `oc get clusterrolebinding default-cluster-account-managed-service-for-syndesis-operator`

## Is an upgrade task required and are there additional steps needed to test this?

Yes. Included.

- [ ] Tested Installation
- [ ] Tested Uninstallation
- [ ] Tested Upgrade

### CODE REVIEW

**Comment by pawelpaszki** [comment]
Triggering the installation on my PDS against this PR

**Comment by pawelpaszki** [comment]
clusterrole & clusterrolebinding are present after installation

**Comment by david-martin** [comment]
@odra Rebased, will need re-approval.
I'm giving it another install spin as there was a conflict on rebase around the image pull secret for fuse.
I'll comment here once I'm happy.

**Comment by david-martin** [comment]
@odra respin of install went well

**Pull request merged**
