### PR TITLE
Add tests to check syntax

### PR DESCRIPTION
**Pull request by camilamacedo86**
## Motivation
Add tests/checks

## What
- Check syntax
## Why
- Do not allow merge PRs with syntax errors 

## How
Checking it

## Verification Steps
1. Check if the command will be called by travis properly

## Checklist:

- [X] Code has been tested locally by PR requester
- [ ] Changes have been successfully verified by another team member

## Progress

- [X] Finished task
- [ ] TODO

## Additional Notes
Following the test. It is working 100%. Note that the master branch has an error in the syntax and because of this, the error is faced. When the master branch will be fixed then the test will pass. 

screenshot 2018-11-24 at 17 38 53

### CODE REVIEW

**Comment by camilamacedo86** [comment]
@tremes and @trepel 

I do not have permission to add this repo/project to travis. Could you give me a hand here? 

screenshot 2018-11-24 at 10 05 30

**Comment by maleck13** [comment]
@camilamacedo86 activated

**Comment by camilamacedo86** [comment]
@maleck13 done:-) really tks. It is 100% to be merged.

**Comment by maleck13** [comment]
actually ok with this being merged as it is only failing on previous issue

**Pull request merged**
