### PR TITLE
TargetDown Alert Creation

### PR DESCRIPTION
**Pull request by obrienrobert**
## Additional Information
[INTLY-9947](https://issues.redhat.com/browse/INTLY-9947)

- Creation of 2 new target down alerts: `TargetDown` and `BlackboxTargetDown`
- Each alert must be verified independently

#### TargetDown
- Install using this branch, ensuring that when both the `TargetDown` and `BlackboxTarget` alerts are created, they are not firing during installation
- Ensure none of the Prometheus targets are in a `DOWN` state:  `Prometheus -> Status -> Targets`
- To trigger the alert, we need to place one of the scrape targets in a `DOWN` state. For example, this can be achieved by changing the port number in one of the product deployments so that the incorrect `hostname:port` is being scraped:

     - In the `enmasse` namespace, navigate to the enmasse-operator deployment and scale down the pods to 0
     - Go to the `console deployment -> Environment tab` in the `enmasse` namespace and change the `METRICS_PORT` variable to an different value, i.e. `9093` 
     - Ensure that the alerts fires and the alert message is clear and concise. You can see the alert message by checking the `Show Annotations` checkbox at the top of Prometheus when an alert is firing.

#### BlackboxTargetDown
- We can trigger this alert by changing the port number that the Blackbox target uses to be incorrect (`9115 -> 9116`)
- In the `middleware-monitoring` namespace, scale down the Prometheus Operator to 0 replicas.
- Navigate to `Stateful Sets ->  prometheus-application-monitoring -> Edit YAML` and add/change the following:

   - Under `args` on line 148, add a new list item: `- '--web.listen-address=0.0.0.0:9116'`
   - Change the `containerPort: 9115` on line 154 to be `containerPort: 9116`

- Ensure that **all** of the `BlackboxTargetDown` alerts fire, and the message in the alert is clear and concise.

### Upgrade
- Install the latest release on your cluster
- Upgrade to this branch
- Verify using the verification steps from above

## Checklist

- [x] Updated [Changelog](https://github.com/integr8ly/installation/blob/master/CHANGELOG.md)
- [x] Tested Installation
- [x] Tested Uninstallation
- [ ] Tested or Created follow on for Upgrade

Is an upgrade task required and are there additional steps needed to test this?
- [x] Yes
- [ ] No

### CODE REVIEW

**Comment by obrienrobert** [comment]
@mikenairn @jessesarn this is ready for review.

**Comment by mikenairn** [comment]
@obrienrobert I have done a run through of the install and ran through the verification steps (Thanks for the clear instructions on how to do that), all worked as described, so looks good to me. Going to setup to double check an upgrade now, but it might be worth getting someone from the monitoring team to scan the alert config, since they will likely know the most about it https://github.com/integr8ly/installation/pull/1411/files#diff-af03f9daf3803aa75253761d400173c5

**Comment by david-martin** [comment]
/approve

Warning is fine for these `cause-based` alerts.
The intention is to give information about scrape targets being down if some set of other alerts are all firing.

**Comment by mikenairn** [comment]
Verified upgrade, worked as expected.

/lgtm

**Pull request merged**
