### PR TITLE
AMQ upgrade to 1.7

### PR DESCRIPTION
**Pull request by briangallagher**
## What
Upgrade AMQ from 1.5 to 1.7. 
JIRA: https://issues.redhat.com/browse/INTLY-10567

## How
Update the Ansible script to upgrade from 1.5 to 1.6 and then on to 1.7

## Verify
Scenario 1:
Install this branch onto rhpds 
Confirm RHMI and AMQ 1.7 installed and is working as expected

Scenario 2:
Install master to rhpds
Upgrade rhmi based on this branch
Confirm RHMI and AMQ 1.7 installed and is working as expected

### CODE REVIEW

**Comment by CathalOConnorRH** [comment]
verified both installs as described above. 
/lgtm
[integreatly-upgrade.log](https://github.com/integr8ly/installation/files/6422489/integreatly-upgrade.log)

**Comment by davidffrench** [comment]
@ciaran-byrne It might be a good idea to change the approvers in the https://github.com/integr8ly/installation/blob/master/OWNERS file. It has been too long since I have looked at RHMI 1.x

**Pull request merged**
