### PR TITLE
codeready update

### PR DESCRIPTION
**Pull request by fh-automatron**
Created automatically by jenkins

### CODE REVIEW

**Comment by ciaran-byrne** [comment]
Closing in favour of a new Major version https://issues.redhat.com/browse/INTLY-4589

**Comment by ciaran-byrne** [comment]
Reopening, as inadvertently closed while work was in progress

**Comment by wei-lee** [comment]
To verify:

. Create an Integreatly PDS cluster.
. Login to the CodeReady console and create a new workspace as the evals user.
. Run the upgrade playbook against the cluster.
. Login to the CodeReady console again, and you should see the version number at the bottom of the Dashboard page is showing `2.0.0.GA`.
. Click on the previous created workspace, you will see an error telling you the format of the workspace is not compatible with the current work of workspace.
. You can follow the instructions [here](https://access.redhat.com/documentation/en-us/red_hat_codeready_workspaces/2.0/html/installation_guide/upgrading-codeready-workspaces_crw#upgrading-codeready-workspaces-on-openshift-3-using-the-cli-management-tool_ugrading-codeready-workspaces) to update the workspace, or just delete it and recreate it using the same remote project (if you have one).

**Comment by wei-lee** [comment]
@pb82 can you help review and verify the PR? Thanks.

**Pull request merged**
