### PR TITLE
fix(che): [WARNING] - TASK [include_role : che]

### PR DESCRIPTION
**Pull request by camilamacedo86**
## Motivation
Issue: https://github.com/integr8ly/installation/issues/168

## What
Fix Warning

## Why
The warning is made because both tasks are included together

## How
Create a task for each one

## Verification Steps
1. Get the PR
2. Run the installation script
3. Check that the waring is no longer faced and both tasks worked with success.  

## Checklist:

- [x] Code has been tested locally by PR requester
- [ ] Changes have been successfully verified by another team member 

## Progress

- [x] Finished task
- [ ] TODO

## Additional Notes

screenshot 2018-11-22 at 09 08 07
screenshot 2018-11-22 at 09 07 43

### CODE REVIEW

**Comment by maleck13** [comment]
I think you need to rebase on master

**Comment by maleck13** [comment]
to get the tests passing

**Comment by maleck13** [comment]
This file doesnt seem to exist deploy-persistent-volume.yml seeing error 
TASK [che : Include persistent volume tasks] *************************************************************************
fatal: [127.0.0.1]: FAILED! => {"reason": "Unable to retrieve file contents\nCould not find or access '/home/ec2-user/installation/evals/playbooks/deploy-persistent-volume.yml' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}

**Comment by maleck13** [comment]
Yep we introduced this. I will revert the che change

**Comment by camilamacedo86** [comment]
@maleck13 thank you for your help. I will test it.

**Comment by camilamacedo86** [comment]
@maleck13 shows that it was changed since I am unable to check the warning in the master anyway. Because of this, I think the merge intrude some issue today. I will close the issue too. Thank you to check it.

**Pull request merged**
