### PR TITLE
Upgrade fuse

### PR DESCRIPTION
**Pull request by wei-lee**
## Additional Information
https://issues.redhat.com/browse/INTLY-4265

## Verification Steps
As the verifier of the PR the following process should be done:

### Installation Verification
- Ensure the author of the PR has attached a log of the installation run from his branch to the jira or pr and check that it exited as expected.
- Verify the fresh installation is correct on cluster provided by PR author 
### Upgrade Verification
- After installation verification, notify the PR author to begin an upgrade on their cluster
- Ensure the developer of the PR has attached a log of the upgrade run from his branch to the jira or pr and check that it exited as expected. 
- If possible, look at the tasks that ran and see they match the PR
- Verify the upgrade is correct on cluster provided by PR author 

## Is an upgrade task required and are there additional steps needed to test this?

- [ ] Yes
- [ ] No

- [ ] Tested Installation
- [ ] Tested Uninstallation
- [ ] Tested or Created follow on for Upgrade

### CODE REVIEW

**Comment by wei-lee** [comment]
@ciaranRoche FYI. Feel free to squash these commits if you prefer.

**Comment by wei-lee** [comment]
@ciaranRoche FYI. Feel free to squash these commits if you prefer.

**Comment by david-martin** [comment]
@ciaranRoche If you're taking over this PR, I've 1 question.
Should these changes land on master first (if not already there), or are the very specific to this upgrade?

**Comment by ciaranRoche** [comment]
@david-martin sorry, only seeing your comment now. 

The current changes Wei had where specific to Fuse 7.5 and Fuse-Online 1.8.13. We could merge them back to master if needs be. But with the new releases, we should be able to get this upgrade playbook merged back to master tomorrow for Fuse 7.5.1 and Fuse-Online 1.8.16

**Comment by ciaranRoche** [comment]
@wei-lee I have verified the following 

- Sign in with multiple users of different permissions to fuse console
- Image streams to be correct and point to latest
- Latest version of images and operator
- Correct postgres version

I did not see any other errors and I successfully completed WT1 and created integreations.

I am leaving this open for now as release testing does not start back till the 2nd of January. I will leave it open for you to reverify before we merge it back

**Comment by davidffrench** [comment]
I am approving based on verification between Ciaran and Wei

/lgtm
/approve

**Pull request merged**
