### PR TITLE
Upgrading Enmasse to v0.24.1

### PR DESCRIPTION
**Pull request by pmccarthy**
**Summary**
- Upgrading EnMasse version to 0.23.2
- Removing artifacts directory
- Adding EnMasse role

### CODE REVIEW

**Comment by maleck13** [comment]
**Verification steps**

delete enmasse ns
run installer

**Comment by maleck13** [comment]
Can't merge currently https://github.com/EnMasseProject/enmasse/issues/1950

**Comment by maleck13** [comment]
@pmccarthy I will try bumping to 0.24.0 which was released two days ago

**Comment by maleck13** [comment]
@pmccarthy this is blocked until this lands https://github.com/EnMasseProject/enmasse/pull/1952 so I think we actually will want to look at upgrading to 0.24.1 
Wondering if getting 0.24.0 working will speed us up for when this issue is fixed?

**Comment by maleck13** [comment]
I did unfortunately that blew up during installation. Not sure why

**Comment by pmccarthy** [comment]
@maleck13 I've added support for v0.24.1 now and everything comes up as expected in the Enmasse namespace. Could you run through some validation steps to see if the issues reported previously have been resolved?

**Comment by maleck13** [comment]
doing full installation now and will go through the walkthough then

**Comment by david-martin** [comment]
Trying this out too, in the context of verifying the following new features:

* enmasse console can be embedded in an iframe (can set the xframeoptions and csp in realms ahead of creation time)
* openshift as the default idp when logging in (skip the option to choose 'OpenShift'

**Comment by david-martin** [comment]
enmasse console for a test user shows in iframe when the right headers are configured in the keycloak configmap.

Also, it automatically logged in. So all good from me.

image

Configmap value I used for `browserSecurityHeaders` key was:

```
{"xFrameOptions":"","contentSecurityPolicy":"default-src 'self' *.apps.waterford-862c.openshiftworkshop.com localhost"}
```

**Comment by maleck13** [comment]
@pmccarthy the uninstall currently fails with 
```
The task includes an option with an undefined variable. The error was: 'enmasse_namespace' is undefined
```

**Comment by maleck13** [comment]
Still trying to verify this hitting issues with the node js app

**Comment by maleck13** [comment]
@pmccarthy close to ready to merge now, want to run this new version against pds and then test the walkthrough with all the fixes in place for this change

**Comment by david-martin** [comment]
:tada:

**Pull request merged**
